### ISSUE TITLE
Does this even work?

### ISSUE THREAD

**Issue by smrtsmrf** [rikulo/socket.io-client-dart#1]
I tried just a basic server and client using the example code (fixing the typos), and I can't get it working. It complains about a bool vs null issue in socket_io_client.dart line 53. I fixed that by changing it to check if opts['forceNew'] != null || opts['force new connection'] != null, but then there's another error about "type '() => dynamic' is not a subtype of type 'EventHandler' of 'handler'"
Direction please?!

**Comment by jumperchen** [comment]
After this fixed, you have to run `pub get` to update [the socket.io-dart project](https://github.com/rikulo/socket.io-dart) as well.

**Comment by smrtsmrf** [comment]
thanks!
