### ISSUE TITLE
Try to connect to `wss://...:443` but get error `Connection to 'https://...:0` was not upgraded

### ISSUE THREAD

**Issue by jerryzhoujw** [rikulo/socket.io-client-dart#102]
I'm trying to connect to a WebSocket service with url like `wss://[host]:443/[path]`

but get `WebSocketException`:  `Connection to 'https://[host]:0/[path]` was not upgraded to websocket

**Comment by jumperchen** [comment]
You should use `https://[host]:443/[path]` instead.

**Comment by jerryzhoujw** [comment]
@jumperchen   do you mean event it's WebSocket ?   

Is there any reason ?

**Comment by jumperchen** [comment]
> @jumperchen do you mean event it's WebSocket ?

Yes, I think.

> Is there any reason ?

This library is porting of [Socket.io client](https://socket.io/docs/client-api/), so you may refer to its document, if it mentioned.

**Comment by jerryzhoujw** [comment]
Thank you. @jumperchen .

I found the similar Q & A on [socket-io-attempting-to-connect-through-https-instead-of-wss-and-getting-an-error](https://stackoverflow.com/questions/59246885/socket-io-attempting-to-connect-through-https-instead-of-wss-and-getting-a)

I get the point.

**Comment by alinoaimi** [comment]
I am facing the same issue,

I have the socket url set to: https://api.mydomain.com

however, it is trying to connect to 
https://api.mydomain.com:0/socket.io/?EIO=4&transport=websocket#

It should have not added port 0, when visiting the page from the browser and removing the port
https://api.mydomain.com/socket.io/?EIO=4&transport=websocket#

it works, it is also working perfectly from my vuejs web version.

I think the library is somehow adding the port 0, to some urls which is causing the issue.

my code:
```
    socket = io(
        'https://api.mydomain.com',
        OptionBuilder()
            .setTransports(['websocket']) // for Flutter or Dart VM
            .disableAutoConnect() // disable auto-connection
            .setExtraHeaders({'foo': 'bar'}) // optional
            .build());

    socket.onConnect((_) {
      debugPrint('connected to the websocket');
      socket.emit('msg', 'test');
    });
    
    socket.onConnectError((data)  {
      debugPrint("CONNEcTION ERROR");
      debugPrint(data.toString());
    });
```

The error message:
```
flutter: CONNEcTION ERROR
flutter: WebSocketException: Connection to 'https://api.mydomain.com:0/socket.io/?EIO=4&transport=websocket#' was not upgraded to websocket
```

**Comment by 0x0-14** [comment]
@alinoaimi Did you happen to find any solution?
