### ISSUE TITLE
Dart is 16 times slower than Javascript

### ISSUE THREAD

**Issue by zeroprofit** [rikulo/socket.io-client-dart#105]
Hi,

I'm not sure if Dart websocket performance is bad or the Dart socket.io performance is bad but I did a performance test running a stream client using this dart library and a stream client using javascript library against a node stream server.  I noticed Dart is around 16 times slower.

You can run your own test using my repo here:  https://github.com/zeroprofit/dart_vs_js

Can someone here enlighten me?

Thanks.

**Comment by marianoarga** [comment]
Really interesting, looking forward to know more about this

**Comment by jumperchen** [comment]
The code you used will do serialization each time the chunk is sent, it’s why the performance is worse.
FYI: This example should run fast by using ‘emitWithBinary’ with data chunk only -  https://github.com/rikulo/socket.io-client-dart/issues/85#issuecomment-623888409

**Comment by zeroprofit** [comment]
There's no serialization in my code.  I push List<Int> through emit.  I added the non-stream version of javascript and dart to simplify.  Using only a single emit to upload a 5MB file already loaded in memory.  On the server side, I commented out fs.writeFile so I only test transport layer.  Result is the same.  Dart 9.8s vs Javascript 0.5s.  Dart websocket performance is terrible.

Language: JAVSCRIPT
Size in bytes: 5186254
Elapsed in ms: 479

Language: DART
Size in bytes: 5186254
Elapsed in ms:  9883

**Comment by zeroprofit** [comment]
I use "emitWithBinary" on Dart.  Results are as follow (Dart 3.1s vs Javascript 0.5s) :

Language: JAVSCRIPT
Stream block size: 65 * 1024
Size in bytes: 5186254
Elapsed in ms: 479

Language: DART
Stream block size: 65 * 1024
Size in bytes: 5186254
Elasped in ms:  3101
