### ISSUE TITLE
Pushing a to private socket doesnt work flutter nodejs

### ISSUE THREAD

**Issue by FeezyHendrix** [rikulo/socket.io-client-dart#107]
```
io.to(socket_id).emit('user-sent-message', payload);
```

Doesn't work on flutter but works well on web

**Comment by jumperchen** [comment]
Have you took a look at the [README.md](https://github.com/rikulo/socket.io-client-dart/blob/master/README.md) first ?

**Comment by hrishiksh** [comment]
Websocket and socketIO is a bidirectional communication between server and client. A client can't communicate with other client directly. 
As This socket.op-client-dart is a client side library, It can't perform your task. You have to use server side package of socket.io for this. I recommend go for nodejs and socket.io combination.
