### ISSUE TITLE
Need dispose method for clearing resources

### ISSUE THREAD

**Issue by shashikantdurge** [rikulo/socket.io-client-dart#108]
There were memory leak issues in iOS when using this plugin.
Fixed it after using clearListeners()

No proper guide on freeing the resources. 

Can we have dispose method in align with flutter ? where it will clearListeners, destroy, close, disconnect...

**Comment by jumperchen** [comment]
The code seem to be there already - https://github.com/rikulo/socket.io-client-dart/blob/5297bbf702c65e22d4079429c6fde7150b7c60f7/lib/src/manager.dart#L432-L445
which will invoke `engine#onClose()` to clear all the listeners - https://github.com/rikulo/socket.io-client-dart/blob/5297bbf702c65e22d4079429c6fde7150b7c60f7/lib/src/engine/socket.dart#L687

**Comment by shashikantleher** [comment]
`close()` does not call `clearListeners()` due to which there was memory leak in iOS.
We have faced this issue in prod, took 2 days to figure out the issue for memory leak which was causing iOS crashes

**Comment by jumperchen** [comment]
@shashikantleher you mean `transport.clearListeners()` was not called or someone else?

**Comment by shashikantleher** [comment]
`socket.clearListeners()`
