### ISSUE TITLE
I can't emit an event

### ISSUE THREAD

**Issue by cakmakfatih** [rikulo/socket.io-client-dart#109]
I am using Flutter to replace an existing project written in Kotlin. There is a part where we use socket.io. And to implement it to Flutter I've tried several different libraries (adhara_socket_io, socket_io_client, flutter_socket_io, itzam_socket_io).

None of them seems to work. Server is running using NestJS. And I am able to connect to the server. And I also am able to listen to the events that are fired by the server. But server does not receive my events.

This is how I create the socket

```
final socket = IO.io(params.url, <String, dynamic>{
  'transports': ['websocket'],
  'autoConnect': false,
  'query': params.query,
});
```

Then I start listening to events,

```
socket.on(SocketEvent.CONNECT, parser.gameWillStart);
socket.on(SocketEvent.GAME_WILL_START, parser.gameWillStart);
socket.on(SocketEvent.NEXT_QUESTION, parser.nextQuestion);
socket.on(SocketEvent.SEND_NEXT_QUESTION, parser.sendNextQuestion);
socket.on(SocketEvent.GAME_TIMER, parser.gameTimer);
...
```

Then I call ```socket.connect()``` and onConnect fires, I can establish the connection.

All this part is working, parsing the events getting the data etc. Then I try to emit events doing,

```
if (args == null)
    socket.emit(event);
else
  socket.emit(event, json.encode(args));
```

Which also gets called without having an exception. But server does not receive the fired event. I have triple checked every event name, checked the arguments I send. Tried sending them both encoded and not encoded, none of them worked.

But when I try to call ```socket.emit("ping")```, or any event that is pre-defined, it works. Only the events we defined on server-side are not received.

Everything is the same with the Kotlin side in terms of logic, but on Flutter I'm not able to emit.

And also, on ```AndroidManifest.xml``` I've tried adding ```android:usesCleartextTraffic="true"``` to application tag but it didn't help either. I've tried running on physical devices, which also did not help. I've tried running on iOS emulator which didn't help too.

Connection is made to an ```https``` server.

```
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
   ...
   socket_io_client: ^0.9.10
```

**Turns out the documentation had 1 character missing on the key event. Everything works fine :D

**Comment by hasyabv** [comment]
Facing the same issue... any idea what can be done?
