### ISSUE TITLE
Can I bypass or allow certificate for connection establishing ?

### ISSUE THREAD

**Issue by terapaht** [rikulo/socket.io-client-dart#110]
I have a server that serving usual RESTful APIs and socketIO on a normal HTTP protocol, and have an Nginx service serving an HTTPS with self-signed certificate.

It might be an server-side problem about certificate generating but in normal API I'm using I can use http lib (or dio) to create a security context and pass it into http handler to allow my created cert file on my device(I'm testing on android).

I wonder that is there a way to pass my own security context, http context or my self-signed certificate into this lib for establishing a connection to socketIO server serving on my https server?

Error message(Same as error from calling http lib without bypassing cert)
`I/flutter (23444):  HandshakeException: Handshake error in client (OS Error:
I/flutter (23444): 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:354))`

**Comment by harshbarnwal** [comment]
I am facing same problem, did you get any solution?

**Comment by terapaht** [comment]
> I am facing same problem, did you get any solution?

I'm now using global httpClient overriding, Solution in topic below.
https://github.com/flutter/flutter/issues/19588

This is not a proper approach but is the only way to make it work for me right now :'(

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#cannot-connect-https-server-or-self-signed-certificate-server
