### ISSUE TITLE
clent how do listing  ack rq from server

### ISSUE THREAD

**Issue by lmr520** [rikulo/socket.io-client-dart#111]
clent how do listing  ack rq from server

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/blob/master/lib/src/socket.dart#L141

For example,
```
socket.emitWithAck('event', data, ack: (response) {})
```

**Comment by lmr520** [comment]
Thanks very much ,my trouble is how on listening  ack rq from server  , fortunately I founded 

   socket.on('sss', (data) {
      final dataList = data as List;
      final ack = dataList.last as Function;
      ack(res);
    });
but only for  have event with message and ack from serve，severs hope clent on listening  sign  ack
not have event name

**Comment by jumperchen** [comment]
By design of the `socket.io` JS API, it requires a ack with an event name, so you can just give it with any character with/without data to fulfill your requirement.

**Comment by hatemragab** [comment]
> Thanks very much ,my trouble is how on listening ack rq from server , fortunately I founded
> 
> socket.on('sss', (data) {
> final dataList = data as List;
> final ack = dataList.last as Function;
> ack(res);
> });
> but only for have event with message and ack from serve，severs hope clent on listening sign ack
> not have event name

is this part work on Dart 

final ack = dataList.last as Function;
ack(res);
how to pass callback from server side

**Comment by hello-ring** [comment]
same question，In nodeJs I write like this
`var map = JSON.parse(msg);
  map['call'] = (abc)=>{};
`
However, such data types do not seem to be supported
What should the server do
