### ISSUE TITLE
WebSocketException: Connection to 'https://myurl:0/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket

### ISSUE THREAD

**Issue by Snofkin** [rikulo/socket.io-client-dart#113]
I am not able to connect to socket.I have attached my problem here.
https://stackoverflow.com/questions/63902629/unable-to-connect-to-the-socket-with-socket-io-client

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#usage-flutter

**Comment by Snofkin** [comment]
well i have tried as per your recommendation but still got the same problem.

```
class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}
```

```
void main() {
  HttpOverrides.global = new MyHttpOverrides();
  runApp(MyApp());
}
```

**Comment by zeeolek** [comment]
I have the same problem.
The exception says: "Connection to 'http://192.168.10.103:3000/socket.io/?sid=xxx&EIO=3&transport=websocket#' was not upgraded to websocket"
Without sid param everything is fine, but after i've added this one my param to url (http://192.168.10.103:3000/?sid=xxx) I'm facing this problem.
The exception is throwing from class IOWebSocketTransport in method: 
` @override
  void doOpen() async {
    var uri = this.uri();
    var protocols = this.protocols;

    try {
      ws = await WebSocket.connect(uri,
          protocols: protocols, headers: extraHeaders);
    } catch (err) {
      return emit('error', err);
    }`

According to socket.io doc, such solution with param is recommended eg. for auth dest: https://socket.io/docs/client-api/#With-query-parameters

**Comment by jumperchen** [comment]
@zeeolek 

This example works for me
```
 var socket = io.io('http://myIPAddress:3000', <String, dynamic>{
    'transports': ['websocket'],
    'query': 'sid=xxx&foo=bar'
  });
```

**Comment by paulhuang1102** [comment]
I face the same issue.
Using https://github.com/socketio/socket.io-client on web
```
const socket = io.connect('https://myapi/room?userId=1');
socket.on('connect', function() {
  //  ....
})
```
work perfectly, but use this on Flutter app like
```
 socket = IO.io('https://myapi/room?userId=1', <String, dynamic>{
      'transports': ['websocket'],
      'autoConnect': true,
      // 'extraHeaders': {'foo': 'bar'} // optional
    });
```
got connect error
```
WebSocketException: Connection to 'https://myapi:0/socket.io/?userId=1&EIO=3&transport=websocket#' was not upgraded to websocket
```

**Comment by jumperchen** [comment]
@paulhuang1102 Have you tried this? https://github.com/rikulo/socket.io-client-dart#cannot-connect-https-server-or-self-signed-certificate-server

**Comment by paulhuang1102** [comment]
@jumperchen yes, I have tried. Then I used `http` instead of `https`, and got same result.

**Comment by jumperchen** [comment]
@paulhuang1102
Which server and version are you using? please provide more info. about your env.
From my env. everything works well.
Or you can provide a runnable env. which is better for us to identify this issue.

**Comment by zeeolek** [comment]
@jumperchen I've tried your code with pass sid param to query position, but the result is exactly the same - exception like above, because in result in the place where the exception occurs we have ofc path: ws://192.168.10.103:3000/socket.io/?sid=xxx&EIO=3&transport=websocket
I'm using the newest ver. socket_io_client 0.9.11
I'm not sure if that problem is directly related to this lib, because on google we can find similar troubles from people does not use this lib, eg here: https://stackoverflow.com/questions/58946101/websocketexception-connection-to-http-localhost1234-ws-was-not-upgraded-t
If I can provide more info just let me know.

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/issues/74#issuecomment-608054167
he encountered the same issue before.

**Comment by paulhuang1102** [comment]
@jumperchen I used Node.js server and Apache.
Can I contact you in confidence, and provide my runnable env?

**Comment by paulhuang1102** [comment]
@jumperchen I used Node.js server and Apache, and I found the problem is my Apache configuration about websocket.
Thank you for your help!
