### ISSUE TITLE
latest dart update

### ISSUE THREAD

**Issue by yurybo** [rikulo/socket.io-client-dart#115]
Last update of the dart/flutter broke socket.io-client. it times-out. Ran few unchanged older versions of my code which were previously working - timeout. Downgraded (> flutter downgrade) flutter/dart to previous version - everything works as expected again.

**Comment by jumperchen** [comment]
@yurybo which version are you using?

**Comment by yurybo** [comment]
0.9.10

¯\(ツ)/¯
W // https://www.0w8.dev (https://link.getmailspring.com/link/A9EC67E7-D826-44B4-8671-AC13D9E5C28A@getmailspring.com/0?redirect=https%3A%2F%2Fwww.0w8.dev&recipient=cmVwbHkrQVFMWE5aM1dWTEZJRkdDTEZGTDM1SEY1UDdGSUJFVkJOSEhDVVRFU09VQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by jumperchen** [comment]
@yurybo  sorry, I mean Dart or Flutter version.

**Comment by yurybo** [comment]
Flutter: 1.20.4
dart: Dart SDK version: 2.9.2 (stable) (Wed Aug 26 12:44:28 2020 +0200) on "macos_x64"

¯\(ツ)/¯
W // https://www.0w8.dev (https://link.getmailspring.com/link/640E9B1A-9E4D-41D4-B8F9-4A73EA3F6A61@getmailspring.com/0?redirect=https%3A%2F%2Fwww.0w8.dev&recipient=cmVwbHkrQVFMWE5aMjJCUjVLVlFBVTJMUzYyQUY1UDdHQ0xFVkJOSEhDVVRFU09VQHJlcGx5LmdpdGh1Yi5jb20%3D)

**Comment by jumperchen** [comment]
@yurybo 

My test project upgrade Flutter from `1.17.1` to `1.20.4` with Dart `2.9.2` and it works for me without any error.
I am using `socket_io_client: 0.9.11` version.

**Comment by yurybo** [comment]
I'll upgrade from .10 to .11 and try. Thank you for reacting :)
And - thank you for an awesome module!

Best,
yury

¯\(ツ)/¯
W // https://www.0w8.dev (https://link.getmailspring.com/link/C4F75874-97D1-4A3F-A27F-A9F37B714144@getmailspring.com/0?redirect=https%3A%2F%2Fwww.0w8.dev&recipient=cmVwbHkrQVFMWE5aMkczSkQ1UVlJSElEUTZaTTU1UDdNVlpFVkJOSEhDVVRFU09VQHJlcGx5LmdpdGh1Yi5jb20%3D)
