### ISSUE TITLE
join

### ISSUE THREAD

**Issue by mrleesin** [rikulo/socket.io-client-dart#12]
How to do like this

socket.join('some room');

?

**Comment by jumperchen** [comment]
You should use that code at server side - https://github.com/rikulo/socket.io-dart
Just as same as using - https://socket.io/docs/rooms-and-namespaces/#Joining-and-leaving

**Comment by mrleesin** [comment]
I use nodejs socketio on server
So, there is no client join() on flutter client

**Comment by jumperchen** [comment]
Is it available at JS client? 
From their official site, the join method is only available at server side, it's not related to flutter or dart.

**Comment by idragon81** [comment]
@jumperchen is right. You need to emit a message from the client and listen to that message on the server. On receiving that message you should perform the join. It is not the responsibility of the client
