### ISSUE TITLE
Add support for Windows, mac and Web

### ISSUE THREAD

**Issue by rupamking1** [rikulo/socket.io-client-dart#120]
Add support for Windows, mac and Web

**Comment by jumperchen** [comment]
This library works as expected, doesn't it?
So what's your question? please tell us more details.

**Comment by rupamking1** [comment]
Please add Ping feature in your Package. That is too helpful to check server.

**Comment by jumperchen** [comment]
It's already there - https://github.com/rikulo/socket.io-client-dart/blob/5297bbf702c65e22d4079429c6fde7150b7c60f7/lib/src/engine/socket.dart#L529
