### ISSUE TITLE
I changed socket.extraHeaders ,local socket changed  but server get extraHeaders no changed

### ISSUE THREAD

**Issue by lmr520** [rikulo/socket.io-client-dart#123]
Step1

  static changeImHeader() {
    socket.io.options['extraHeaders'] = {
      'foo': 'bar',
      'token': token
    }; // Update the extra headers.
    socket.io
      ..disconnect()
      ..connect(); // Reconnect the socket manually.
  }

but server no changed

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/issues/58#issuecomment-587259534
It works in my env.

**Comment by lmr520** [comment]
I m sorry  that server is error
