### ISSUE TITLE
  socket_io_client  for socket connect triggering multiple times .

### ISSUE THREAD

**Issue by dvmjoshi** [rikulo/socket.io-client-dart#124]
I am using the socket_io_client library for the socket connection in the flutter app. for example

 connectToSocket() {
Socket socket = io('http://xyxz', <String, dynamic>{
    'query': {"sdsxyz"} // optional
  });
socket.connect();
 }
calling this method at initState. for socket connect. but socket connection trigger(socket connected socket disconnected)multiple times at the server end.
I want that socket connection should be called once for the normal flow of data.

**Comment by arbaker2** [comment]
When creating the socket it autoConnects by default. So the socket is connecting and then you are calling the connect function on it for a second time. If you do not want this behavior either set the 'autoConnect' property to false and then call socket.connect(), or do not call socket.connect() and let the socket connect automatically.

**Comment by dvmjoshi** [comment]
I tried both ways to set the 'auto-connect' property to false and then call socket.connect(), or do not call socket.connect() and let the socket connect automatically. but the same problem and its automatic socket disconnected multiple times 

.

**Comment by mriaz764** [comment]
I'm also facing same issue and below are logs printing 

DEBUG_KEY Socket connect
2020-10-20 16:45:23.134 10251-10329/l/flutter: DEBUG_KEY Socket disconnect
2020-10-20 16:45:27.237 10251-10329/I/flutter: DEBUG_KEY Socket connect
2020-10-20 16:47:05.149 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
2020-10-20 16:47:09.848 10251-10329/I/flutter: DEBUG_KEY Socket connect
2020-10-20 16:48:57.437 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
2020-10-20 16:49:00.502 10251-10329/I/flutter: DEBUG_KEY Socket connect
2020-10-20 16:49:41.498 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
2020-10-20 16:49:46.535 10251-10329/I/flutter: DEBUG_KEY Socket connect
2020-10-20 16:50:42.858 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
2020-10-20 16:50:46.987 10251-10329/I/flutter: DEBUG_KEY Socket connect

**Comment by dvmjoshi** [comment]
'transports': ['polling'], is not working and kindly check the above problem also it will very helpful.

**Comment by dvmjoshi** [comment]
> I'm also facing same issue and below are logs printing
> 
> DEBUG_KEY Socket connect
> 2020-10-20 16:45:23.134 10251-10329/l/flutter: DEBUG_KEY Socket disconnect
> 2020-10-20 16:45:27.237 10251-10329/I/flutter: DEBUG_KEY Socket connect
> 2020-10-20 16:47:05.149 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
> 2020-10-20 16:47:09.848 10251-10329/I/flutter: DEBUG_KEY Socket connect
> 2020-10-20 16:48:57.437 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
> 2020-10-20 16:49:00.502 10251-10329/I/flutter: DEBUG_KEY Socket connect
> 2020-10-20 16:49:41.498 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
> 2020-10-20 16:49:46.535 10251-10329/I/flutter: DEBUG_KEY Socket connect
> 2020-10-20 16:50:42.858 10251-10329/I/flutter: DEBUG_KEY Socket disconnect
> 2020-10-20 16:50:46.987 10251-10329/I/flutter: DEBUG_KEY Socket connect
> 
> my flutter code
> 
> socket = io("https://fat-skunk-36.loca.lt/", <String, dynamic>{
> 'transports': ['websocket'],
> 'autoConnect': false,
> });
> socket.connect();
> socket.on('connect', (_) {
> Utils.showLog("Socket connect");
> });

do you get any solution for it.

**Comment by jumperchen** [comment]
@dvmjoshi 
Have you read this before? https://github.com/rikulo/socket.io-client-dart/blob/master/README.md#usage-flutter

@mriaz764 Have you checked this before? https://github.com/rikulo/socket.io-client-dart/blob/master/README.md#cannot-connect-https-server-or-self-signed-certificate-server

**Comment by dvmjoshi** [comment]
@jumperchen   thank you for responding with  'transports': ['websocket'], its working fine but with default config and  'transports': ['polling'], connection triggers multiple time did you have any idea about this strange working.

**Comment by jumperchen** [comment]
@dvmjoshi 
`'transports': ['polling']` does not support in Flutter, by default this library was designed for dart web, but dart web is not popular than Flutter; the `polling` mechanism is ported from [Socket.io JS](https://socket.io/), which is using Ajax way to implement, but it's not allowed in `dart:io` library.

If you would like to use the `polling` way in Flutter, your contribution is welcome :)

**Comment by dvmjoshi** [comment]
@jumperchen  thank you so much for helping out.

**Comment by hatjs880328s** [comment]
yep,i have the same question , and i set ['websocket'] to Transports.

every 30secs disconnect and  then reconnect ..
