### ISSUE TITLE
connect_error on Android & macOs & iOS

### ISSUE THREAD

**Issue by wottpal** [rikulo/socket.io-client-dart#127]
I am on the flutter dev-channel (1.24.0-3.0.pre) and I tried connecting to my socket.io server on the following plattforms:

* ❌ Android 11 (API 30)
* ❌ macOS 10.15.7
* ❌ iOS 14.1
* ✅ Chrome 86.0.4240.111

It only worked within chrome, on all other I got `connect_error`. When will other platforms be better supported?

Thanks!

**Comment by wottpal** [comment]
Am I doing anything wrong? I'm connecting with the following code: 

```
  static final SOCKET_URL = 'http://localhost:5000';

  IO.Socket socket = IO.io(SOCKET_URL, <String, dynamic>{
    'transports': ['websocket']
  });
```

**Comment by jumperchen** [comment]
Flutter app is run inside a virtual machine, which cannot work with `localhost`.

**Comment by wottpal** [comment]
🤯
Thank you, I’ll try it with a deployed version of my server again and report it here!

**Comment by wottpal** [comment]
Ok update: I got it to work with *all platforms* except macOS :( Still `connect_error` so I guess it's a duplicate of #101? Any ideas @rikulo? Thanks!

**Comment by jumperchen** [comment]
@wottpal please read - https://flutter.dev/desktop#setting-up-entitlements

FYI: https://github.com/flutter/flutter/issues/47606#issuecomment-568522318

By adding the following key into the to file `*.entitlements` under directory `macos/Runner/`
```
<key>com.apple.security.network.client</key>
<true/>
```

**Comment by wottpal** [comment]
Awesome it works, thanks! Please add this to the README.md though :)
