### ISSUE TITLE
Usage with flutter web not working

### ISSUE THREAD

**Issue by pbler20** [rikulo/socket.io-client-dart#128]
Hi, 
I'm trying to setup socket.io-client-dart for flutter web. I used the example code and changed it for usage with flutter. 

```
socket = IO.io('<URL>', <String, dynamic>{
      'transports': ['websocket']});
socket.on('connect', (_) {
      print('connect');
      socket.emit('msg', 'test');
});
socket.on("connect_error", (msg) => print(msg));
socket.on('event', (data) => print(data));
socket.on('disconnect', (_) => print('disconnect'));
socket.on('fromServer', (_) => print(_));
```

As output I get: 
`{msg: websocket error, desc: null, type: TransportError}`

Running the same code with target Android works fine. Resulting in  `connect`.

**Comment by dvmjoshi** [comment]
try polling for web or check from the backend side that polling or WebSocket is supported.
'transports': ['polling']

**Comment by pbler20** [comment]
Thank you! The problem was a wrong config of the backend (CORS).

**Comment by marinat** [comment]
> Thank you! The problem was a wrong config of the backend (CORS).

What config for CORS did you use?

**Comment by naveensaigit** [comment]
I was facing the exact same issue, and I realized that it was because I was using Socket.io v4 in the backend, which is incompatible with socket_io_client v1.0.2. I had to add the following to make it work -

Use socket_io_client v2.0 (beta as of writing this) in `pubspec.yaml` on the client side.
``` yaml
socket_io_client:
    git:
      url: git://github.com/rikulo/socket.io-client-dart
      ref: 2.0-beta-nullsafety
```

Enable CORS on the server side.
``` javascript
// Import all libraries required

const app = express();
const server = http.createServer(app);

// Enable CORS for any domain
const io = socketio(server, {
  cors: {
    methods: ['GET', 'PATCH', 'POST', 'PUT'],
    origin: true,
  }
});
```

**Comment by Rajputazad** [comment]
> Thank you! The problem was a wrong config of the backend (CORS).

please help me same problem
