### ISSUE TITLE
Flutter, ping packets are not sent in release version

### ISSUE THREAD

**Issue by sommoMicc** [rikulo/socket.io-client-dart#13]
In release version (flutter), no ping packets are sent, so connection is dropped by server

**Comment by shingohu** [comment]
@jumperchen  I have the same issue

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'asUint8List' was called on null.
Receiver: null
Tried calling: asUint8List()
#0      PacketParser.encodePacket (package:socket_io_common/src/engine/parser/parser.dart:72)
#1      IOWebSocketTransport.write.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:90)
#2      _GrowableList.forEach (dart:core/runtime/libgrowable_array.dart:171)
#3      IOWebSocketTransport.write (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:89)
#4      Transport.send (package:socket_io_client/src/engine/transport/transport.dart:102)
#5      Socket.flush (package:socket_io_client/src/engine/socket.dart:586)
#6      Socket.sendPacket (package:socket_io_client/src/engine/socket.dart:630)
#7      Socket.ping (package:socket_io_client/src/engine/socket.dart:552)
#8      Socket.setPing.<anonymous closure> (package:socket_io_client/src/engine/socket.dart:541)
#9      _rootRun <…>

```

**Comment by shingohu** [comment]
@sommoMicc Have you solved the problem

**Comment by sommoMicc** [comment]
@shingohu no, I've switched to another library which has a similar interface: adhara_socket_io (url: [https://github.com/infitio/flutter_socket_io](url)). It has a compilation issue with iOS, but if you look in the "Issue" section, someone has proposed a patch and it works.

**Comment by shingohu** [comment]
@sommoMicc I have also seen this library, and I also submitted an issue. I found the behavior of this library on IOS and Android is inconsistent, and the Socketio library of Android has not been updated for two years, and there are many problems, so I dare not use it in my project. Back to the above question, I don't know if you have the same problem as me. I modified the code in parse.dart to just add a null judgment, and then it works. I don't know what the consequence will be. I expect the author's answer
```
if (packet['data'] != null) {
      if (packet['data'] is Uint8List) {
        return encodeBuffer(packet, supportsBinary, callback,
            fromClient: fromClient);
      } else if (packet['data'] is Map &&
          packet['data']['buffer'] is ByteBuffer) {
        packet['data'] = (packet['data']['buffer'] as ByteBuffer).asUint8List();
        return encodeBuffer(packet, supportsBinary, callback,
            fromClient: fromClient);
      } else if (packet['data'] is ByteBuffer) {
        packet['data'] = (packet['data'] as ByteBuffer).asUint8List();
        return encodeBuffer(packet, supportsBinary, callback,
            fromClient: fromClient);
      }
    }
```

**Comment by jumperchen** [comment]
@shingohu Does this issue happen in release version only? Which env. are you using? (iOS or Android)

**Comment by jumperchen** [comment]
And the code above, in dart lang, the null value should not pass that if condition `packet['data'] is ByteBuffer`

For example,
```
// Dart lang
main() {
  Foo a = null;
  final dataMap = {'data': a};
  if (dataMap['data'] is Foo) {
    print(true);
  } else {
    print(false);
  }
}
class Foo {}
```

It will print `false`

**Comment by shingohu** [comment]
@jumperchen yes，run as release in iOS
'''
 print([packet['data'] is ByteBuffer]);
 print([packet['data'].runtimeType is ByteBuffer]);
'''
the packet['data'] = null 
and the print is   
true
false

**Comment by jumperchen** [comment]
It sounds like a bug in flutter only for `ByteBuffer` class.
I will post an issue to Flutter.

**Comment by shingohu** [comment]
@jumperchen I print the result in flutter 
```
 ByteBuffer a = null;
    var dataMap = Map<String,dynamic>();
    dataMap['data'] = a;
    if (dataMap['data'] is ByteBuffer) {
       print(true);
    } else {
      print(false);
    }
```
the result is **false**

**Comment by shingohu** [comment]
@jumperchen yes，I tried again and again。  in release mode  and debug mode the result is different 
I have submitted an issue [here](url)

**Comment by sommoMicc** [comment]
Have you tried with the new version of flutter (1.2)?

**Comment by lkho** [comment]
I have tried this in flutter 1.2.1, dart 2.1.2, the problem still exists.
And also, adding a null check beforehand can solve it.
Should we patch this library for a quick workaround of the flutter optimization?

**Comment by sommoMicc** [comment]
In my opinion, patching the library is a good idea, so we can start using
it.

Il ven 15 mar 2019, 08:50 LKHO <notifications@github.com> ha scritto:

**Comment by jumperchen** [comment]
Run `pub upgrade socket_io_common` should solve this.
