### ISSUE TITLE
Catching authentication error not working

### ISSUE THREAD

**Issue by steve-cahn** [rikulo/socket.io-client-dart#133]
I'm trying to authenticate when a flutter application connects to a node.js server. I added this:
```javascript
_io.use(function (socket, next) {
		if (authentication()) {
		     next(user);
		} else {
                         This runs but nothing happens on client side....
			next(new Error('Authentication error'));
		}
	});
```
and this in flutter
```dart
    socket.on('error', (data) {
      print(data);
    });
    socket.on('connect_error', (data) {
      print(data);
    });

    socket.onDisconnect((e) => print(e));
```
But the errors never get logged. How can I catch an error

**Comment by TobseW** [comment]
Hi Steve,

I'm experiencing the same issue on v2.0.0-beta.3.
Did you fix the problem on your side? And if so, could you please let me know what you did to get it up and running?

Thanks a lot!
Tobi

**Comment by TobseW** [comment]
I found the issue. 
For anyone else having the same issue: 
the connect_error-callback only works as a callback for errors occurring inside a connect()-call from this library (client side errors only!). 
It does NOT report any error messages sent by the backend during the connection process. Errors sent by the backend are sent to the onError()-callback ('error').

Hope this helps someone else in the future 👍
