### ISSUE TITLE
Unable to connect to Tcp server

### ISSUE THREAD

**Issue by gionchat** [rikulo/socket.io-client-dart#135]
![image](https://user-images.githubusercontent.com/58280808/103062117-4490c680-45e8-11eb-826d-89c7512b36da.png)
My Code:

            // Dart client
            IO.Socket socket = IO.io('http://192.168.2.5:8266');
            socket.onConnect((_) {
              print('connect');
              socket.emit('msg', 'test 123');
            });
            socket.on('event', (data) => print(data));
            socket.onDisconnect((_) => print('disconnect'));
            socket.on('fromServer', (_) => print(_));

**Comment by jumperchen** [comment]
Did you run this code in Browser or Dart VM env.?

If running with Dart VM or Flutter, please specify the transports: ['websocket'].
More details, please have a look at https://github.com/rikulo/socket.io-client-dart/blob/master/README.md

**Comment by gionchat** [comment]
> Did you run this code in Browser or Dart VM env.?
> 
> If running with Dart VM or Flutter, please specify the transports: ['websocket'].
> More details, please have a look at https://github.com/rikulo/socket.io-client-dart/blob/master/README.md

Thank you very much!

**Comment by gionchat** [comment]
Thanks!
