### ISSUE TITLE
Unhandled Exception: FormatException:

### ISSUE THREAD

**Issue by au-top** [rikulo/socket.io-client-dart#144]
Unhandled Exception: FormatException: H 

* server

```

import ws from 'ws';
const wsProt=3211;
const wsServer= new ws.Server({
    port:wsProt,
    host:'0.0.0.0'
},()=>console.log('WebSocketServer Run'));
wsServer.on('connection',(c)=>{
c.send('Hello');
// console.log(c);
});


```

* flutter
```

class _connect {
  _connect(){
  }
  link(){
    IO.Socket socket = IO.io('ws://172.16.5.10:3211',
        IO.OptionBuilder()
        .setTransports(['websocket']) // for Flutter or Dart VM
        .setExtraHeaders({'foo': 'bar'}) // optional
        .build());
    socket.onConnect((_) {
      print('connect');
      socket.emit('msg', 'test');
    });
    socket.on('event', (data) => print(data));
    socket.onDisconnect((_) => print('disconnect'));
    socket.on('fromServer', (_) => print(_));
  }
}
final Connect = _connect();

```

**Comment by au-top** [comment]
E/flutter ( 9969): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FormatException: H
E/flutter ( 9969): #0      num.parse (dart:core/num.dart:474:26)
E/flutter ( 9969): #1      PacketParser.decodePacket (package:socket_io_common/src/engine/parser/parser.dart:147:18)
E/flutter ( 9969): #2      Transport.onData (package:socket_io_client/src/engine/transport/transport.dart:120:31)
E/flutter ( 9969): #3      IOWebSocketTransport.addEventListeners.<anonymous closure> (package:socket_io_client/src/engine/transport/io_websocket_transport.dart:67:7)
E/flutter ( 9969): #4      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 9969): #5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 9969): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 9969): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 9969): #8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 9969): #9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter ( 9969): #10     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter ( 9969): #11     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter ( 9969): #12     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
E/flutter ( 9969): #13     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 9969): #14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 9969): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 9969): #16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter ( 9969): #17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter ( 9969): #18     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:69:11)
E/flutter ( 9969): #19     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
E/flutter ( 9969): #20     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
E/flutter ( 9969): #21     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
E/flutter ( 9969): #22     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:121:24)
E/flutter ( 9969): #23     _HttpDetachedStreamSubscription._maybeScheduleData.<anonymous closure> (dart:_http/http_parser.dart:178:20)
E/flutter ( 9969): #24     _rootRun (dart:async/zone.dart:1182:47)
E/flutter ( 9969): #25     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9969): #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9969): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9969): #28     _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9969): #29     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9969): #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter ( 9969): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter ( 9969): #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 9969): #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 9969):

**Comment by au-top** [comment]
Can't be shared with other websocket servers?

**Comment by jumperchen** [comment]
Which socker.io servers are you using?

**Comment by au-top** [comment]
my no use  socker.io server  my use websocket server ,  socker.io server is no websocket server ?
my use nodejs "ws" server

```
import ws from 'ws';
```

**Comment by arno-dev** [comment]
do you have a code missing ? I got that issue but only when i add a parser on server side

**Comment by au-top** [comment]
thanks ,I used other WS pakcage
