### ISSUE TITLE
Example Error

### ISSUE THREAD

**Issue by mulieli** [rikulo/socket.io-client-dart#146]
![image](https://user-images.githubusercontent.com/24307960/106351255-240a0980-6316-11eb-8817-2b280a2b7176.png)
![image](https://user-images.githubusercontent.com/24307960/106351264-35ebac80-6316-11eb-9520-368cf83a0bfa.png)

**Comment by jumperchen** [comment]
Here is latest one - https://github.com/rikulo/socket.io-client-dart/blob/master/example/README.md#usage
