### ISSUE TITLE
Every time I try to do anything it connects me as a new Client to the socket and the messages which are sent are repeating again and again, Please Help

### ISSUE THREAD

**Issue by prkhrv** [rikulo/socket.io-client-dart#15]
![carbon 25](https://user-images.githubusercontent.com/31151040/52904610-5a970880-3254-11e9-990a-8a2b6cb2b816.png)

**Comment by ekeshi1** [comment]
That maybe because you are connecting inside the Build method , which is run everytime the state of the widget changes. Try handling your sockets outside the Build method.

**Comment by prkhrv** [comment]
Thank You @ekeshi1 I have figured it out, it's now working fine. :)

**Comment by kevinespaldon** [comment]
Do you mind sharing your solution @prkhrv ?

**Comment by prkhrv** [comment]
@kevinespaldon Hi, I just switched to another Package called adhara_socket_io
link:- https://pub.dartlang.org/packages/adhara_socket_io#-readme-tab

It works fine by creating a single instance of the socket in the initState. You can use that too.

**Comment by kevinespaldon** [comment]
@prkhrv Thank you! Will try this one out.
