### ISSUE TITLE
Problem with setQuery in socket io version 3.0

### ISSUE THREAD

**Issue by hugoyair** [rikulo/socket.io-client-dart#150]
When I try to use setQuery (object), I can´t connect me in the server, but when I don´t use setQuery I can. I don´t know why. 

I can use setHeaders, but It´s not the best option to do it. 

I´m using the last version 2.0.0-beta.2 but my server is socket version 3.0

**Comment by jumperchen** [comment]
any example?

**Comment by majunor** [comment]
I had the same problem. The offending line seems to be in manager.dart lines 365-367. It adds the query to the the namespace which in my case resulted in the server responding with unknown namespace. Unfortunately this results in the socket class simply ignoring the packet (socket.dart line 218) and not sending an error event. So, it seems like you just can't connect.
Commenting out the lines in manager.dart solves my problem, even though i'm not sure if that causes any side effects...

**Comment by jumperchen** [comment]
Fixed in 2.0-beta branch and release `socket_io_client 2.0.0-beta.3`

**Comment by hugoyair** [comment]
Thank you so much, I´ll use it to try it.
