### ISSUE TITLE
Is the Flutter StreamBuilder example correct?

### ISSUE THREAD

**Issue by misteroak** [rikulo/socket.io-client-dart#152]
Hi,

I'm not an expert, and probably missing something, but I suspect the StreamBulder example might have bug?

In the example, it says:
`socket.on('event', (data) => streamSocket.addResponse);`
But, shouldn't it be:
`socket.on('event', (data) => streamSocket.addResponse(data));`

**Comment by jumperchen** [comment]
FYI: https://dart.dev/guides/language/language-tour#functions-as-first-class-objects
