### ISSUE TITLE
Problem with Flutter 2.0

### ISSUE THREAD

**Issue by Sn0wBiT** [rikulo/socket.io-client-dart#161]
I'm using socket.io-client in old Flutter version 1.22 and it work very well but after update to 2.0 socket.io can't connect to server again.

**Comment by ssaleh21** [comment]
Having similar issues with iOS after I upgraded flutter, connect request doesn't even reach server

**Comment by ssaleh21** [comment]
I found the problem to be caused by the server being HTTP rather than HTTPS
This didn't seem to be an issue with the older Flutter SDK, but was stopping my iOS device from connecting to the server
Was able to work around it by allowing insecure connections
You can find a similar solution here https://stackoverflow.com/questions/64172791/flutter-insecure-http-is-not-allowed-by-platform

**Comment by Sn0wBiT** [comment]
> I found the problem to be caused by the server being HTTP rather than HTTPS
> This didn't seem to be an issue with the older Flutter SDK, but was stopping my iOS device from connecting to the server
> Was able to work around it by allowing insecure connections
> You can find a similar solution here https://stackoverflow.com/questions/64172791/flutter-insecure-http-is-not-allowed-by-platform

I got this. I'll check it. Thank you very much

**Comment by diego-garro** [comment]
If your backend is constructed with `node`, take in count that `npm i socket.io` installs the latest version (^3.0.0), that is not working with Flutter. You must to install the version 2.3.0 of socket.io with `npm i socket.io@2.3.0`. That may fix the problem.

**Comment by ptheofan** [comment]
Same issue here (though using the package for the first time). I'm using socket.io 2.3.0 on iOS emulator. The target domain:port is http but I've configured the iOS build to allow all non-secure network activity. Same domain is perfectly reachable with the http package (REST api).

```dart
_socket = IO.io('$host:28081/?token=$jwt', IO.OptionBuilder()
      .setTransports(['websocket'])
      .build());
```

No errors, but no connection also, unfortunately.

**Comment by Sn0wBiT** [comment]
> If your backend is constructed with `node`, take in count that `npm i socket.io` installs the latest version (^3.0.0), that is not working with Flutter. You must to install the version 2.3.0 of socket.io with `npm i socket.io@2.3.0`. That may fix the problem.

Well my node server is running 2.4.1 and it work well with Flutter 1.22. Do I need to downgrade to 2.3.0 for Flutter 2.0 ?

**Comment by diego-garro** [comment]
> > If your backend is constructed with `node`, take in count that `npm i socket.io` installs the latest version (^3.0.0), that is not working with Flutter. You must to install the version 2.3.0 of socket.io with `npm i socket.io@2.3.0`. That may fix the problem.
> 
> Well my node server is running 2.4.1 and it work well with Flutter 1.22. Do I need to downgrade to 2.3.0 for Flutter 2.0 ?

Exactly!!
