### ISSUE TITLE
Can't connect socket server

### ISSUE THREAD

**Issue by SalihCanBinboga** [rikulo/socket.io-client-dart#164]
Hello, i'm using latests version but i can't connect socket server. I'm searched but i did'nt find. 
Where could the problem be? (My firewall is closed)

Socket: https://paste.ubuntu.com/p/5gws6Y5zZk/
Flutter Client: https://paste.ubuntu.com/p/w95MswcKz5/
Log: https://paste.ubuntu.com/p/vb6WwpPzSN/

**Comment by jumperchen** [comment]
`localhost` in Flutter Client? it should be IP address or domain name.

**Comment by mavyfaby** [comment]
Same from me it doesn't connect.

**Comment by jumperchen** [comment]
@mavyfaby FYI: https://github.com/rikulo/socket.io-client-dart#version-info
Did you use the correct version on both client and server?

**Comment by mavyfaby** [comment]
Yes, I'm using `socket.io v3.1.2` and for `socket.io-client-dart v2.0.0-beta.3-nullsafety.0`. 

After like 5-10 seconds it shows timeout:
`I/flutter (30614): timeout`

Yes, my server is running and here is my code for the server:

```js
const express = require('express') ;
const app = express() ;
const server = require('http').createServer(app);
const socket = require('socket.io')(server);

socket.on("connection", function(client) {
    console.log("New connection: " + client.id);	
});

server.listen(3000, function() {
    console.log("Listening on port 3000");
});
```

and my client code:

```dart
MaterialButton(
    color: GoogleColors.blue,
    onPressed: () {
      try {
        Socket socket = io('http://192.168.1.102:3000', 
          OptionBuilder()
             .setTransports(['websocket'])
             .disableAutoConnect()
             .build()
          );

          socket.onConnectError((data) {
            print(data);
          });

          socket.connect();    
        }
          catch (e) {
            print("Socket error: $e");
          }
    },
    child: Text("Connect", style: TextStyle(color: Colors.white)),
),
```

**Comment by jumperchen** [comment]
@mavyfaby FYI: https://github.com/rikulo/socket.io-client-dart/issues/161#issuecomment-791845561

**Comment by mavyfaby** [comment]
I think this issue caused by the Flutter insecure http:

```
E/flutter (13305): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Bad state: Insecure HTTP is not allowed by platform: http://192.168.1.102/
```
I fixed this problem by adding `android:usesCleartextTraffic="true"` in `AndroidManifest.xml` file and it now finally worked.

**Comment by SalihCanBinboga** [comment]
@jumperchen found the problem. my problem is the versions are not correct and i working 10.0.2.2 local server. thank you
