### ISSUE TITLE
Upgrade to UUID 2.0.0

### ISSUE THREAD

**Issue by kevinespaldon** [rikulo/socket.io-client-dart#17]
Hi,

Do you mind updating the dependency to UUID from 1.0.3 to 2.0.0?
 
I have version conflicts with packages that use UUID 2.0.0.

EDIT: for clarification, I'm talking about **socket_io_common 0.9.0+2**

[here](https://i.imgur.com/cpmYgGW.png)

**Comment by jumperchen** [comment]
Please run `pub upgrade socket_io_common` to solve this issue, and `socket_io_client` won't depend on uuid anymore.

**Comment by kevinespaldon** [comment]
Thanks I appreciate your quick response.

Have a great day!
