### ISSUE TITLE
WebSocketException: Connection to url was not upgraded to websocket

### ISSUE THREAD

**Issue by marcoberetta96** [rikulo/socket.io-client-dart#170]
I can't figure out what does the following error mean.

```
WebSocketException:
Connection to 'http://192.168.1.8:8080/socket.io/?EIO=3&transport=websocket#'
was not upgraded to websocket
```

My code is this.

```
_socket = io(
  NODE_JS_SERVER_URL,
  OptionBuilder().setTransports(['websocket']).disableAutoConnect().enableForceNew().build(),
);
_socket.connect();
```

I use a NodeJs server:
```
const app = express();
const http = require('http').createServer(app);
const io = require('socket.io')(http);
io.on('connection', socket => { console.log("new connection"); }

```

**Comment by jumperchen** [comment]
Which client and server versions are you using?
Have you seen the guide before? - https://github.com/rikulo/socket.io-client-dart#troubleshooting

**Comment by marcoberetta96** [comment]
I have already tried with "Cannot connect "https" server or self-signed certificate server" but nothing changed.

Flutter dependency is `socket_io_client: ^0.9.12`
NodeJs dependency is `"socket.io": "^2.4.1"`

**Comment by shajedulislam** [comment]
@marcoberetta96 I am facing same issue. Have you solved it?

**Comment by marcoberetta96** [comment]
@shajedulislam I've just updated the nodejs dependency to the latest version. Actually it is 3.0.0
