### ISSUE TITLE
flutter: WebSocketException: Connection to 'https://udlogger.ubedev.com:0/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket

### ISSUE THREAD

**Issue by shajedulislam** [rikulo/socket.io-client-dart#179]
**Code at app:**

```
 socket = io(
      'https://udlogger.ubedev.com',
      OptionBuilder()
          .setTransports(['websocket'])
          .disableAutoConnect()
          .enableForceNew()
          .build(),
    );

    socket.connect();
```

**Code at server:**

```
const app = require('express')()
const http = require('http').createServer(app)
app.get('/', (req, res) => {
    res.send("Node Server Is Running")
})
const socketio = require('socket.io')(http)
socketio.on("connection", (userSocket) => {
    id=userSocket.id;
    console.log('New Socket Connection | ID: ',id);
    userSocket.on("send_message", (data) => {
      console.log('Message: ',data);
      userSocket.emit("receive_message", data)
    })
})
const PORT=5577
http.listen(PORT)

```

**Output at server:**

`New Socket Connection | ID:  sqzTKFFqn-QsPEgoAAEJ`

**Error at app:** 

`flutter: WebSocketException: Connection to 'https://udlogger.ubedev.com:0/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket`

I already tried **"https" server or self-signed certificate server** solution but not helping. I have hosted my node application in a shared cpanel. It works with web browser but not in mobile app.

**Comment by abinmittu** [comment]
@shajedulislam I am having the same problem. Did you solve the issue?

**Comment by shajedulislam** [comment]
@abinmittu you are facing it in local host or any live server. If live then which server?

**Comment by abinmittu** [comment]
Live server. Node js server  with ```socket.io:3.0.3``. I am also using ```socket_io_client: ^2.0.0-beta.4-nullsafety.0``` on client side. Did you solve the issue? I am sure it is some version incompatibility.

**Comment by evaleiraswembii** [comment]
same for me

**Comment by shajedulislam** [comment]
> Live server. Node js server  with ```socket.io:3.0.3```. I am also using ```socket_io_client: ^2.0.0-beta.4-nullsafety.0``` on client side. Did you solve the issue? I am sure it is some version incompatibility.

If its a shared hosting then it will not work. Shared hosting will not let you use socket. If you can get administrative access then possible. I had to buy windows server then it worked.
