### ISSUE TITLE
socket.on('event', (...) {...}) is called twice.

### ISSUE THREAD

**Issue by kevinespaldon** [rikulo/socket.io-client-dart#18]
So I have my listeners on `initState`...    

```
socket.on('synchronizedata', (packet) {
      print('packet of type ${packet['packetKind']}!-> $packet');

      _syncMessages(context, _message);
    });
```

but when the server emits `synchronizedata`, the code above is fired twice. Any thoughts? Initially, I have them on the `build` method, but after reading [issue #15], I placed them into `initState`.

Any thoughts?

**Comment by kevinespaldon** [comment]
Hmm... I might have solved this accidentally.

For some reason I removed `socket_io` import and the calls are not duplicated anymore. Will wait for a couple more days to see if the issue persists.

**Comment by kevinespaldon** [comment]
Issue no longer encountered (weirdly enough)... Closing!

**Comment by JonataCSantos** [comment]
@madqueendany Hi, I'm having the same problem but I only got this import:

`import "package:socket_io_client/socket_io_client.dart" as IO;`

Did you use something different?
