### ISSUE TITLE
Cannot connect to socket server

### ISSUE THREAD

**Issue by Ian-Munashe** [rikulo/socket.io-client-dart#181]
I upgraded my application to use null-safety. Now the application is failing to connect to my socket server. I'm getting no errors when I run my application.

**Comment by samiulllah** [comment]
same issue here

**Comment by iqbalabdurrazaq** [comment]
yess, i'm same issue, not getting errors.

**Comment by qcuong97** [comment]
yesss, i'm same issue, i getting error 'timeout'

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#version-info

**Comment by jumperchen** [comment]
Please check your versions on both client and server to work with a correct version.

**Comment by tirth-stasis** [comment]
Server is using `4.0.1` (NodeJs)

Which version of `socket.io-client-dart` works with that.

**Comment by Abdullahfoysal** [comment]
this following version works for me:
node: v15.13.0
dependency:
"socket.io": "^2.3.0"

flutter: socket_io_client: ^1.0.1

**Comment by applevinc** [comment]
@jumperchen I can't connect to the nodejs server 4.4.1

**Comment by applevinc** [comment]
> Please check your versions on both client and server to work with a correct version.

i have done this but I still get the same results

**Comment by applevinc** [comment]
why is there no error to know what exactly is happening???

i have been stuck on this for over a week and there is no other package I can use

**Comment by applevinc** [comment]
> @applevinc Here lists my test case, which works with Nodejs server 4.4.1
> 
> ## Nodejs version
> ```
> ├── express@4.17.3
> ├── socket.io-client@4.4.1
> └── socket.io@4.4.1
> ```
> 
> With the example - https://github.com/rikulo/socket.io-client-dart/blob/2.0-beta-nullsafety/test_nodejs/server.js
> 
> ## Flutter version
> ```
>  Flutter (Channel dev, 2.11.0-0.1.pre, on macOS)
>     • Flutter version 2.11.0-0.1.pre at 
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision b101bfe32f (2 days ago), 2022-02-16 07:36:54 -0800
>     • Engine revision e355993572
>     • Dart version 2.17.0 (build 2.17.0-69.2.beta)
>     • DevTools version 2.10.0-dev.1
> ```
> 
> Dependencies...
> 
> ```
>   async 2.8.2
>   boolean_selector 2.1.0
>   characters 1.2.0
>   charcode 1.3.1
>   clock 1.1.0
>   collection 1.15.0
>   cupertino_icons 0.1.3 (1.0.4 available)
>   fake_async 1.2.0
>   flutter 0.0.0 from sdk flutter
>   flutter_test 0.0.0 from sdk flutter
>   js 0.6.4
>   logging 1.0.2
>   matcher 0.12.11
>   material_color_utilities 0.1.3 (0.1.4 available)
>   meta 1.7.0
>   path 1.8.1
>   sky_engine 0.0.99 from sdk flutter
>   socket_io_client 2.0.0-beta.4-nullsafety.0
>   socket_io_common 2.0.0
>   source_span 1.8.1 (1.8.2 available)
>   stack_trace 1.10.0
>   stream_channel 2.1.0
>   string_scanner 1.1.0
>   term_glyph 1.2.0
>   test_api 0.4.9
>   typed_data 1.3.0
>   vector_math 2.1.1 (2.1.2 available)
> ```
> 
> With the example - https://gist.github.com/jumperchen/037a180c8d08a6e795b34eee65ed8ef3
> 
> After run and click a button on the Flutter app, the console prints:
> 
> ```
> I/flutter (21256): connected
> I/flutter (21256): send text to server
> I/flutter (21256): fromServer {"key":"hello","value":"world"}
> ```

I have  the same set-up but still no luck

**Comment by jumperchen** [comment]
@applevinc `IO.io('http://YOUR_IP:3000'` you cannot set `localhost` nor `127.0.0.1` in this line

**Comment by applevinc** [comment]
The person on the backend mentioned something about raw socket.....I don't know if that affects it

**Comment by jumperchen** [comment]
maybe you can add a logger to see what happens.
For example,

```

import 'package:logging/logging.dart';
import 'package:stack_trace/stack_trace.dart';

@override
  void initState() {
    initLogger();
    // ... omitted
   }

initLogger([Level level = Level.FINEST, RegExp? match]) {
  Logger.root.level = level;
  Logger.root.onRecord.listen((LogRecord rec) {
    if (match != null && !match.hasMatch(rec.loggerName)) {
      return; // ignore
    }
    String lineInfo = '';
    Trace trace = new Trace.current();
    final frame = _findCallerFrame(trace);
    if (frame != null) {
      if (frame.uri.pathSegments.isNotEmpty) {
        String filename = frame.uri.pathSegments.last;
        String line = frame.line != null ? ':${frame.line}' : '';
        lineInfo = '[$filename$line] - ';
      }
    }
    print('${rec.level.name}: ${rec.time} ${rec.loggerName}: $lineInfo ${rec.message}: ${rec.error ?? ''}\n${rec.stackTrace ?? ''}');
  });
}

Frame? _findCallerFrame(Trace trace) {
  bool foundLogging = false;

  for (int i = 0, len = trace.frames.length; i < len; ++i) {
    Frame frame = trace.frames[i];

    bool loggingPackage = frame.package == 'logging';
    if (foundLogging && !loggingPackage) {
      return frame;
    }

    foundLogging = loggingPackage;
  }

  return null;
}

```

**Comment by applevinc** [comment]
@jumperchen it's connecting now 🔥🔥🔥

**Comment by applevinc** [comment]
The socket was changed from raw to normal socket

**Comment by applevinc** [comment]
@jumperchen Thanks for the help 🙏
