### ISSUE TITLE
How to send data before connect?

### ISSUE THREAD

**Issue by Drolegc** [rikulo/socket.io-client-dart#182]
I want to try this but in dart
(Javascript)
```
async onUsernameSelection(id) {
                this.usernameAlreadySelected = true;

                let url = "http://localhost:1337/users/" + id
                var response = await fetch(url)
                response = await response.json()
                console.log(response)
                console.log(socket.auth)

                socket.auth = {
                    user: response
                };
                socket.connect();
            },
```

**Comment by jumperchen** [comment]
https://github.com/rikulo/socket.io-client-dart/pull/177 ?
If this feature, it supports on `2.0.0-beta.4-nullsafety.0` version

**Comment by Drolegc** [comment]
Damn, thanks

**Comment by shelzTimesignature** [comment]
> #177 ? If this feature, it supports on `2.0.0-beta.4-nullsafety.0` version

but how coz i installed version 2.0.0-beta.4-nullsafety.0 and still its saying auth not found 
I did the following
socket.auth={}

**Comment by shelzTimesignature** [comment]
i finally figure it out 
socket.io.options['extraHeaders']={
"user_id":"your user id you want to pass"
}

this is how you pass credentials to the server before connect
