### ISSUE TITLE
handshake.auth is missing in OptionBuilder

### ISSUE THREAD

**Issue by pradt** [rikulo/socket.io-client-dart#183]
Hi I'm using OptionBuilder to set the options for a socket connection and I noticed that there wasn't a method available to set the auth option as documented at https://socket.io/docs/v4/server-api/#socket-handshake

is there a way to do this via any other option or would I need to craft the map manually ?

**Comment by Drolegc** [comment]
#177 
If you are not using nullsafety, my solution was to add an extra header with an stringified object

**Comment by jumperchen** [comment]
Try to use latest [v2.0.0-beta.4-nullsafety.0](https://github.com/rikulo/socket.io-client-dart/releases/tag/v2.0.0-beta.4-nullsafety.0) to work with handshake.auth issue.

**Comment by njavilas2015** [comment]
Hello how to use?

socket = IO.io('https://api.$domain/token/',
            OptionBuilder()
                .setTransports(['websocket'])
                .setAuth({'token': token})
                .build()
        );

this correct implementation?

**Comment by pradt** [comment]
@jumperchen thank you - how do I reference that release in pubspec.yaml ?

**Comment by radvansky-tomas** [comment]
Can you please explain all that versioning mess ? Can't we just merge those old 2.0.0 branches and start over ?
