### ISSUE TITLE
flask+socketio: Connection times out

### ISSUE THREAD

**Issue by C-monC** [rikulo/socket.io-client-dart#186]
Hi,

I'm using the example code mentioned in #36 but am failing to get the flutter/dart client working. I am using a socketio 1.0.0.
Is it possible that there are permission problems? I am unsure of how to troubleshoot this.

Using a python socketio server + python client works from two different pc's.

The server:
```
from aiohttp import web
import socketio

sio = socketio.AsyncServer()
app = web.Application()
sio.attach(app)

async def index(request):
    """Serve the client-side application."""
    with open('index.html') as f:
        return web.Response(text=f.read(), content_type='text/html')

@sio.event
def connect(sid, environ):
    print("connect ", sid)

@sio.event
async def chat_message(sid, data):
    print("message ", data)

@sio.event
def disconnect(sid):
    print('disconnect ', sid)

app.router.add_static('/static', 'static')
app.router.add_get('/', index)

if __name__ == '__main__':
    web.run_app(app, port=5000)
```
The client (flutter):
```
import 'dart:convert';
import 'package:socket_io_client/socket_io_client.dart' as io;

class SocketService {
  createSocketConnection() {
    var socket = io.io('http://192.168.8.11:5000', {
      'transports': ['websocket'],
      'autoConnect': true,
    })
      ..on('connect', (_) {})
      ..on('disconnect', (_) {});
    print(socket.id);
    print(socket.connected);
    //socket.off('active_bands');
    socket.emit('add_band', {'name': 'fluttertutorial'});
    socket.on('active_bands', _eventHandler);
  }

  void _eventHandler(Object object) {
    print(object);
  }
}

main() {
  SocketService sockser = SocketService();
  sockser.createSocketConnection();
}

```

**Comment by jumperchen** [comment]
You may check whether it's a version issue on both client and server.

* https://github.com/miguelgrinberg/python-socketio#version-compatibility
* https://github.com/rikulo/socket.io-client-dart#version-info

**Comment by C-monC** [comment]
Thanks for the help.

For others trying to get python socketio working with flutter.

`pip install python-socketio==4.6.1`
and 
`socket_io_client: ^1.0.1`
works.

**Comment by abinmittu** [comment]
@C-monC 

Do you know which Flask-SocketIO version is compatible with socket_io_client. I am using ```Flask-SocketIO==4.3.2``` on server side and  ```socket_io_client: ^1.0.1```.  It is not working.

**Comment by C-monC** [comment]
Yes, Flask-socketio needs to be in the 3.*.* range. Use the newest one - I think 3.6.2. 

type pip install flask-socketio==3.3.3.3 (any version that won't match) to list the versions.
