### ISSUE TITLE
Websocket error if cross origin enable

### ISSUE THREAD

**Issue by Drolegc** [rikulo/socket.io-client-dart#187]
Im having this error
 `I/flutter (18800):  :: CONNECTING ERROR :: WebSocketException: Connection to 'http://192.168.1.8:3000/socket.io/?EIO=3&transport=websocket#' was not upgraded to websocket`

when I enable cross-origin

`const io = require("socket.io")(httpServer, {
    origins: ["*:*"]
})` (or with localhost)

Version con SocketIO (server) 2.4.0

**Comment by jumperchen** [comment]
I test the following versions, and they work well to me.

**Version**:
* Socket.io Node server: 2.4.1
* Socket.io-client-dart: 1.0.0
* Flutter: 2.1.0-10.0.pre
* Dart: 2.12.3
* sdk: ">=2.7.0 < 3.0.0" without null-safety

**Server example**:
https://github.com/rikulo/socket.io-client-dart/blob/master/test_nodejs/server.js#L15
add the ` { origins: ["*:*"] }` as yours.

Not sure whether you enable or not for this - https://github.com/rikulo/socket.io-client-dart#cant-connect-socket-server-on-flutter-with-insecure-http-connection

**Comment by Drolegc** [comment]
I didn't try to enable that, but this works for me
https://stackoverflow.com/questions/67375849/how-to-connect-my-app-to-socketio-server-if-i-have-cors-enabled/67390287#67390287
