### ISSUE TITLE
socket_io_client not work on flutter version from 2.*

### ISSUE THREAD

**Issue by thoanghung** [rikulo/socket.io-client-dart#196]
I try to connect to nodejs server use socket.io. But it just timeout for Flutter 2.x. When I downgrade flutter to version 1.22.6, it work well
Test env:
-Flutter 2.x
-socket.io server 3.x
-socket.io client 1.0.1

**Comment by BBolaSamy** [comment]
same issue 
@thoanghung how did you solve this issue ? please
