### ISSUE TITLE
Socket not working when I do a pub build

### ISSUE THREAD

**Issue by smrtsmrf** [rikulo/socket.io-client-dart#2]
I've got the socket working when I have my client files running on pub serve through Webstorm. (Although the connection is sometimes finnicky.)

But when I do a pub build so that I can serve up the files from my server, the socket doesn't seem to work at all. 

Here's my (relevant) dart client code:

```
void ngOnInit() {
    name = _routeParams.get('name');
    socket = IO.io('http://localhost:3000');
    socket.connect();
    socket.on('connect', (_) {
      print('Socket connected (client)');
      // need to send something stupid initially so that it will keep listening
      socket.emit('client', 1);

      socket.on('server', (_) => print('handshake'));
      
      countDownTimer = new Timer.periodic(const Duration(seconds: 1), (Timer countDownTimer) {
        countDown--;
        timerMsg = countDown > 0 ? 'BEGIN IN ${countDown}' : 'GO!';

        if (countDown == 0) {
          socket.emit('start game', 2);
          countDownTimer.cancel();
          gameInProgress = true;
          
          gameTimer = new Timer.periodic(const Duration(seconds: 1), (Timer gameTimer) {
            gameTime--;
            gameTimerMsg = gameTime > 0 ? gameTime.toString() : 'END GAME';

            if (gameTime == 0) {
              print('game over');

              
              print('updateLeaderboard');
              Leader player = new Leader(name, 25);
              _leaderboardService.leaders.add(player);
              _leaderboardService.leaders.sort((a, b) => b.score.compareTo(a.score));
              print('about to end game');
              socket.emit('end game', 'i am a string');
              print('should have ended game');
              gameTimer.cancel();
              this._router.navigate(['Leaderboard', player.toMap()]);
            }
          });
        }
      });
    });

    socket.on('new color', (data) {
      print('new color: $data');
      HTML.Animation animation;
      HTML.Element element;
      switch (data) {
        case 1:
          element = green.nativeElement; break;
        case 2:
          element = red.nativeElement; break;
        case 3:
          element = yellow.nativeElement; break;
        case 4:
          element = blue.nativeElement; break;
      }
      animation = element.animate([{"opacity": 100}, {"opacity": 0}], 150);
      animation.play();
    });

    socket.on('point', (_) => score++);
    
    socket.on('ended game', (_) {
      socket.clearListeners();
      socket.disconnect();
    });

    socket.on('disconnected', (_) => print('socket disconnected (server)'));
  
}
```

And here's the errors I'm getting in Chrome:
![screen shot 2017-07-25 at 8 27 15 am](https://user-images.githubusercontent.com/17756776/28577307-a07b0436-7113-11e7-82db-8edcf1e2f4da.png)

**Comment by jumperchen** [comment]
I fixed some issues which may relate to this issue, you can give it a try. (remember to run `pub upgrade ` first), and I also make a test case with a timer to demonstrate the problem you encountered,  but it works well for me on both dartium or browser (compiling to js) environment.

**Comment by NickWu007** [comment]
Hi,

I have been having the same problem, but slightly different.

On `pub serve` things are working fine, but on `pub build`, locally I would get a few 400 errors but eventually succeed to connect. Below is a screenshot:

![screen shot 2018-02-01 at 16 24 04](https://user-images.githubusercontent.com/17936144/35689869-63d75648-076c-11e8-9d2f-7a6636a44a4c.png)

I am also deploying my app on digital ocean VPS and over there I would get a huge number of 400 errors(with same response body), and finally connect after 1 or 2 minutes. Below is a screenshot of network activities on VPS.

![screen shot 2018-01-30 at 20 53 21](https://user-images.githubusercontent.com/17936144/35689966-a78784c6-076c-11e8-8394-7be60507ba13.png)
![screen shot 2018-01-30 at 20 56 02](https://user-images.githubusercontent.com/17936144/35689967-a7a62d22-076c-11e8-8d06-0a6c3edc6cb6.png)

My server is written in node:

```
var app = express()
var server = http.createServer(app);
server.listen(port);
var io = require('socket.io').listen(server);
```

I am using namespaces also, for each client:

```
var socketPath = '/' + req.session.user.username
io.of(socketPath).on('connection', function (socket) {
    ...
}
```

Client:

```
String namespace = 'http://localhost:5000' + socketPath;
print('connecting to $namespace');
socket = IO.io(namespace);
socket.on('connect', (_) {
        print('connected to $namespace');
        ....
}
```

As far as I can see there's very little custom config used. Could you please take a look as this? I can discuss more in detail. This lib is critical for my project, so please help.

Thanks,
Nick

**Comment by jumperchen** [comment]
This issue is fixed in https://github.com/rikulo/socket.io-dart, so you should upgrade them by running `pub upgrade`.
