### ISSUE TITLE
[Question] Is there a way to find list of subscribe event ?

### ISSUE THREAD

**Issue by TheAlphamerc** [rikulo/socket.io-client-dart#207]
In the below code we have two events `onNewMessage` and `onNewNotification`.  Is there a way to find the name of each listener event attached to the socket? If yes then I might be able to avoid subscribing the same event again and again.

```dart

import 'package:socket_io_client/socket_io_client.dart' as IO;

main() {
  // Dart client
  IO.Socket socket = IO.io('http://localhost:3000');
  socket.onConnect((_) {
    print('connect');
    socket.emit('msg', 'test');
  });
  socket.on('onNewMessage', (data) => print(data));
  socket.on('onNewNotification', (_) => print(_));
}
```
Below is the library and flutter version which I am using.
Package version: `socket_io_client: ^2.0.0-beta.4-nullsafety.0`
Flutter version: `Flutter 2.2.3 • channel stable`

**Comment by anchal-td** [comment]
At present, list of listeners is not  available but you can check that event is subscribed or not using `socket.hasListeners("event_name")`.

**Comment by TheAlphamerc** [comment]
Thanks @anchal-td, This works the same as what I was trying to acheive.
