### ISSUE TITLE
socket.onAny feature

### ISSUE THREAD

**Issue by Bunny1376** [rikulo/socket.io-client-dart#209]
hey, hope you best!
I'm using socket package and it is very ok but I need socket.onAny property too

**Comment by jumperchen** [comment]
add a reference - https://socket.io/docs/v3/client-api/index.html#socket-onAny-callback

**Comment by jumperchen** [comment]
refer to https://github.com/rikulo/socket_io_common/releases/tag/v2.0.0, please run `pub upgrade` to upgrade `socket_io_common` to `2.0.0` version to support this.
