### ISSUE TITLE
socket working in Flutter web but not working in flutter when running on android device.

### ISSUE THREAD

**Issue by Boanerges1996** [rikulo/socket.io-client-dart#213]
socket working in Flutter web but not working in flutter when running on android device.

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#usage-flutter

**Comment by Boanerges1996** [comment]
Works perfectly than you @jumperchen. Was using 
`  _socket = io('http://**********', <String, dynamic>{
        'autoConnect': false,
         'transports':["websocket"]
      });
`

 But iit didn't work. Adding the optional builder works for me
