### ISSUE TITLE
1.0.1 _placeholder binary data isn't received correctly 

### ISSUE THREAD

**Issue by Curvel** [rikulo/socket.io-client-dart#214]
I am trying to use my Flutter client to receive byte data sent from my node.js server. The problem is that normal messages arrive, but byte data does not.

Trying to reproduce the behavior in the example app, I noticed that when I send from my server, the byte data is sent through a _placeholder and through a 2nd separate message.

1. message from node.js server
`451-[\"event.response\",{\"id\":\"81907ced-96df-49f5-91d3-4ace1659c658\",\"audioStream\":{\"_placeholder\":true,\"num\":0}}]`
2. message from node.js server `data = {Uint8List} size = 16606`

This messages are received and can be debugged by this package. But are never emitted to the event listeners.

I tried debugging the code of this package but wasn't able to find a fix for it by now. 

Maybe related to closed: https://github.com/rikulo/socket.io-client-dart/issues/167

### Setup
**socket_io_client: ^1.0.1**

[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-DE)
    • Flutter version 2.2.3 at /Users/curvel/dev/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

**Comment by Curvel** [comment]
Okay just saw this [fix](https://github.com/rikulo/socket_io_common/commit/4eb1bbf2f0646de198e16d520bfe0a93674e00d3) for the 2.0 release. I will try to use it on the 1.0 release.

**Comment by Curvel** [comment]
Okay, the fix does actually work!! I will open an PR :)

**Comment by jumperchen** [comment]
Please run `pub upgrade` to fix this issue.
