### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=4099 after switch between connectivity

### ISSUE THREAD

**Issue by nizwar** [rikulo/socket.io-client-dart#215]
I got this error while user changing connectivity from Wifi to Mobile Data or from Mobile data to Wifi :

`[Client] Updating selectors after delegate removal failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 89 named com.apple.commcenter.coretelephony.xpc was invalidated from this process." UserInfo={NSDebugDescription=The connection to service on pid 89 named com.apple.commcenter.coretelephony.xpc was invalidated from this process.}`

This errors will repeated until `ping timeout`, its happened on IOS Devices, is there any way to get through this?

**Comment by jumperchen** [comment]
FYI: https://stackoverflow.com/a/58489809

**Comment by nizwar** [comment]
My case is not using simulator, but IOS Devices (Iphone 12), after all it turns out i believe this one not related with socket and can be ignored
