### ISSUE TITLE
Socket not connecting with SocketIO 4.0.0 on server

### ISSUE THREAD

**Issue by rohitrvayuz** [rikulo/socket.io-client-dart#225]
The lastest release version 1.0.1 on Flutter is not working with server socket.io version 4.0.0

I am not able to connect and listen to events.

@rikulo 
@jumperchen @henrichen @tomyeh @jimmyshiau @fzyzcjy 
@Kavantix @felangel @bruce3x @Oskang09 
@sarru1291 @kerolloz @hrishiksh

**Comment by Djihanegh** [comment]
I have the same problem i have tried socket io client version 1.0.1 in flutter with the socket io in nodejs version 2.4.1 , and tried to upgrade flutter socket io to the 2.0.0-beta.4-nullsafety.0 version with the node js socket io 2.3 version , it didn't worked

here's my code :

```
  static Socket? socket;

  socket = io("wss://url:443", OptionBuilder()
         .setTransports(["polling","websocket"]) 
          .disableAutoConnect()  
          .setExtraHeaders({'authentication':token ,  'Connection': 'upgrade', 'Upgrade': 'websocket'}) 
          .build() );

      // Connect to websocket
      socket?.connect();

```

**Comment by jumperchen** [comment]
@rohitrvayuz FYI: https://github.com/rikulo/socket.io-client-dart#version-info
@Djihanegh you may also take a look at https://github.com/rikulo/socket.io-client-dart/blob/master/README.md first
