### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by lanjiachuan** [rikulo/socket.io-client-dart#23]
Hello author! I have a problem now. When I connect to my own nettySocket.io server using a plugin, I keep disconnecting and disconnecting. I ask if this plugin is developed with reference to 2.1.1 or the latest 2.2.0. How should I solve this situation? The server I am ok in other projects, so I spent 2 days looking for bugs. Found that it is not a server problem. I don't know if you can help

**Comment by lanjiachuan** [comment]
IO.Socket socket;
    var _option={
      "query": "token=${SpHelper.getToken()}",
      "timeout": 150000,
      "autoConnect": true,
      "reconnection": true,
      "forceNew": false,        //是否创建新的连接
      "reconnectionDelay": 3000,//尝试连接 间隔时间
      "reconnectionAttempts": 6,//尝试连接的次数
    };
    debugPrint('connect:连接');
     socket = IO.io(ServerApi.Socket_Io_Server_Url,_option);
     debugPrint('获取socket链接状态:${socket.connected}');
    socket.on('connect', (msg) {
      debugPrint('A获取socket链接状态:${socket.connected}');
      debugPrint('已连接$msg');
      debugPrint('connect:连接成功');
    });

**Comment by jumperchen** [comment]
Which env. are you using this library? flutter or browser?
If in flutter, you have to put `String, dynamic>{'transports': ['websocket']});` as an option,
for example - https://github.com/rikulo/socket.io-client-dart/blob/master/test/io_client.dart#L8

**Comment by lanjiachuan** [comment]
socket.on('offLinemsg', (msgs, ask) => {} 
How is the callback of the on event implemented?

**Comment by jumperchen** [comment]
The code you use should be a server side code (from `socket.io`), however, we implemented this already on Dart part as follows.
```
socket.on('offLinemsg', (data) {
 var ack = data is List && data.last is Function ? data.removeLast()
              : null;
});
```
If the last argument is a function, then it should be the `ack` callback.

**Comment by lanjiachuan** [comment]
I am using socket.on('offLinemsg', (data) {} I need to tell the server that I have signed this message. Your method just judges whether the last is an ack callback. How should I use ack to send a message to the server?

**Comment by jumperchen** [comment]
please refer to https://github.com/rikulo/socket.io-client-dart/issues/24

**Comment by lanjiachuan** [comment]
this.socket.on('pushMsg', (msgs, ask) => {
          if(msgs.originatorId.id!==this.OwnId){
            this.pushMsgSubject.next(msgs);
          }
          ask(msgs.id);
    }
The above is the way I used to use js. But I don't know how to implement this callback in flutter. Also, can you implement the function of webrtc? My app is an instant messaging feature and requires a message sign. In addition, webrtc realizes audio and video calls!

**Comment by jumperchen** [comment]
Your example in dart will be.
```
socket.on('pushMsg', (data) {
  final dataList = data as List;
  final msgs = dataList.first as MyObject;
  final ask = dataList.last as Function;
  if (msgs.originatorId.id != this.OwnId) {
    this.pushMsgSubject.next(msgs);
  }
  ask(msgs.id);
});
```
