### ISSUE TITLE
Can't connect to the server

### ISSUE THREAD

**Issue by ShehanTreineticOfficial** [rikulo/socket.io-client-dart#233]
I am trying to connect nodejs secure socket server to the flutter app.  But it doesn't work. I have tried many ways. Here is my code. Any one know the issue?

**Flutter 2.5.2 • channel stable 
Tools • Dart 2.14.3
Socket IO version - socket_io_client: ^2.0.0-beta.4-nullsafety.0**

```
Socket socket = io(
        'wss://SERVER_URL',
        OptionBuilder()
            .setTransports(['websocket'])
            .disableAutoConnect()
            .setPath("/realtime")
            .setAuth({'token': "$token"})
            .setExtraHeaders({
              'authentication': token,
              'Connection': 'upgrade',
              'Upgrade': 'websocket'
            })
            .enableForceNew()
            .build());

    socket.io.encoder = CustomEncoder();
    socket.io.decoder = CustomDecoder();

    socket.connect();
```

OUTPUT:
socket.connected false
socket disconnect transport close
socket disconnect transport close
socket disconnect transport close
....

**Comment by NicolasCaousGV** [comment]
Are you interpolating the string 'wss://SERVER_URL' with the actual server URL? Can you connect using other clients in the same environment (such as a browser)? Are you certain that there are no network problems between the client and the server?

**Comment by zionnite** [comment]
was able to fix my issue by upgrading the `socket_io_clent: ^1.0.2 ` to `socket_io_client: ^2.0.0-beta.4-nullsafety.0`

**Comment by zionnite** [comment]
> was able to fix my issue by upgrading the `socket_io_clent: ^1.0.2 ` to `socket_io_client: ^2.0.0-beta.4-nullsafety.0`

I engage another issue, 
socket connection is working fine on iPhone but not on android, tried with a physical android device, no luck

**Comment by ShehanTreineticOfficial** [comment]
My issue was in,
```
 socket.io.encoder = CustomEncoder();
 socket.io.decoder = CustomDecoder();
```
 
since this plugin still does not support the encoding features we can't use that. Once I removed the encoding and decoding plugin from the node server and the app this was worked as expected.

**Comment by zionnite** [comment]
> > was able to fix my issue by upgrading the `socket_io_clent: ^1.0.2 ` to `socket_io_client: ^2.0.0-beta.4-nullsafety.0`
> 
> I engage another issue, socket connection is working fine on iPhone but not on android, tried with a physical android device, no luck


The reason my device and emulator was not able to connect to server was because Mac have its different approach how it is done, this link should help anyone who cant connect their android emulator to server on mac

[https://www.panayiotisgeorgiou.net/how-to-connect-localhost-in-your-mac-to-your-android-device-or-android-emulator/](url)
