### ISSUE TITLE
 not connecting to server

### ISSUE THREAD

**Issue by mahdinazmi** [rikulo/socket.io-client-dart#238]
Im using
socket_io_client: ^2.0.0-beta.2 (flutter)
socket.io : 3.1.2 (server)
But when I try to connect to the socket in flutter , nothing happens at all, it does not connect and it does not give an error.

IO.Socket socket = IO.io('http://inodari.satanapp.ir');
socket.connect();
socket.onConnect(() {
print('connect');
socket.emit('msg', 'test');
});
socket.on('status', (data) => print(data));
socket.onDisconnect(() => print('disconnect'));

**Comment by jumperchen** [comment]
Please take a look at README.md first.

**Comment by mahdinazmi** [comment]
> Please take a look at README.md first.

I checked it but my problem is not solved. I am using the package example but as I said it does not work.

**Comment by mahdinazmi** [comment]
> Please take a look at README.md first.

I checked it but my problem is not solved. I am using the package example but as I said it does not work.

**Comment by jumperchen** [comment]
Have you read Flutter section?

**Comment by mahdinazmi** [comment]
> Have you read Flutter section?

Yes , I went completely forward with the document.
But as I said, it does not work at all, even if I write the URL incorrectly, it does not show me an error.

**Comment by mehranshoqi** [comment]
same problem
