### ISSUE TITLE
Works great on local but does not work on server

### ISSUE THREAD

**Issue by mahdinazmi** [rikulo/socket.io-client-dart#241]
In Local, I can easily connect to the socket, but when I upload to the server, it does not connect to the socket.

package versions :
on server : 4.0.1
on flutter : 2.0.0-beta.3-nullsafety.0

**Comment by cickpoo0121** [comment]
I got this problem too, Are you solve this problem finished yet?

**Comment by mahdinazmi** [comment]
@cickpoo0121 
Yes, I fixed the problem.
 I sent a ticket to the server support and they told me to send the port and domain to install the socket.
After they installed, I tested it and it worked properly and there was no problem.
And make sure that the ssl of the domain is active and enter the domain address with https to connect to the socket.
