### ISSUE TITLE
Problem with real device and socket.io in Flutter

### ISSUE THREAD

**Issue by zakariachamakh** [rikulo/socket.io-client-dart#248]
- **socket server version**  :  "socket.io": "^2.4.1" 
-  **socket client version** :  socket_io_client: ^1.0.2
- the same  code work in flutter web  and broken  in android real device and  emulator

**Comment by hrithikwins** [comment]
I am facing the same issue in android real device, while all my Socket APIs work fine in Postman

**Comment by hrithikwins** [comment]
@zakariachamakh try upgrading to  ^2.0.0-beta.4-nullsafety.0 It worked for me in the emulator, might work for you as well
#233
