### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by Gazzolla** [rikulo/socket.io-client-dart#251]
I updated my project to null-safety, but the socket has this error, before I used the adhara package, but there is no null safety support, so I had to migrate to this one, but this error is appearing and I can't find a solution

**WebSocketException: Connection to 'https://APIADDRESS:0/socket.io/?EIO=4&transport=polling#' was not upgraded to websocket**

```
void main() {
  // Dart client

  IO.Socket socket = IO.io(apiAddress, <String, dynamic>{
    // 'query': 'plataform=app',
    'transports': ['polling', 'websocket'],
  });
  socket.onConnect((_) {
    socket.emit('chat message', 'test');
  });
  socket.on('event', (data) => print(data));
  socket.onConnectError((data) => print(data));
  socket.onDisconnect((_) => print('disconnect'));
  socket.on('fromServer', (_) => print(_));
}
```

my package version i: socket_io_client: ^2.0.0-beta.4-nullsafety.0 
sokcet server version is: 4.0.0 in node.js

**Comment by jumperchen** [comment]
`polling` transports only works for web env.

**Comment by Gazzolla** [comment]
My problem was with AWS, some infrastructure parameter, even with polling it worked on mobile, thanks for answering
