### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by X-SLAYER** [rikulo/socket.io-client-dart#254]
I tried to connect on Binance's WebSocket endpoints but I get this error
 **connect_error: WebSocketException: Connection to 'https://stream.binance.com:9443/socket.io/?EIO=4&transport=websocket#' was not upgraded to websocket**
 
 ```dart
 if (_socket != null) _socket!.disconnect();
    _socket = io.io(
      "wss://stream.binance.com:9443/ws/btcusdt@kline_1m",
      io.OptionBuilder()
          .setTransports(['websocket'])
          .enableReconnection()
          .setReconnectionDelay(1000)
          .enableForceNew()
          .build(),
    );
    _socket!.connect();
    _socket!.on(
      "connect",
      (data) => log('Connected $data', name: "SOCKET Connected"),
    );
    _socket!.on(
      "connect_error",
      (data) => log('connect_error: $data', name: "SOCKET Error"),
    );
    _socket!.on(
      "reconnect",
      (data) => log('reconnect: $data', name: "SOCKET Reconnect"),
    );
    _socket!.on(
      "reconnect_failed",
      (data) => log('reconnect_failed: $data', name: "SOCKET Reconnect fail"),
    );
    _socket!.on(
      "reconnect_error",
      (data) => log('reconnect_error: $data', name: "SOCKET Reconnect error"),
    );
    _socket!.on("update", (data) {
      log("Updated $data", name: "SOCKET Updated");
    });
 ```
 
 im using **socket_io_client: ^2.0.0-beta.4-nullsafety.0**

**Comment by Advait1306** [comment]
Are you sure the Binance websocket API uses Socket.io?

**According to Socket.io website:**
Socket.IO is NOT a WebSocket implementation. Although Socket.IO indeed uses WebSocket as a transport when possible, it adds additional metadata to each packet. That is why a WebSocket client will not be able to successfully connect to a Socket.IO server, and a Socket.IO client will not be able to connect to a plain WebSocket server either.

According to my research, Binance doesn't use a socket.io connection. It uses a standard websocket connection. Trying following the example in this cookbook.
https://docs.flutter.dev/cookbook/networking/web-sockets

**Comment by X-SLAYER** [comment]
> Are you sure the Binance websocket API uses Socket.io?
> 
> **According to Socket.io website:** Socket.IO is NOT a WebSocket implementation. Although Socket.IO indeed uses WebSocket as a transport when possible, it adds additional metadata to each packet. That is why a WebSocket client will not be able to successfully connect to a Socket.IO server, and a Socket.IO client will not be able to connect to a plain WebSocket server either.
> 
> According to my research, Binance doesn't use a socket.io connection. It uses a standard websocket connection. Trying following the example in this cookbook. https://docs.flutter.dev/cookbook/networking/web-sockets

Thanks, I just discovered that earlier, and I used the standard WebSocket package instead and it works fine
[web_socket_channel](https://pub.dev/packages/web_socket_channel)
