### ISSUE TITLE
Cannot connect Dart client v2 to Node.js Server v4

### ISSUE THREAD

**Issue by busslina** [rikulo/socket.io-client-dart#257]
My Flutter client is: socket_io_client: ^2.0.0-beta.4-nullsafety.0.
My Server client is: "socket.io": "^4.1.2".

My dart code is the following. Never executes the connect event.
`
Future<void> start() async {
    debug('start() -- Connecting to $serverUrl', tag: debugTag);
    socket = io.io(
        serverUrl, io.OptionBuilder().setTransports(['websocket']).build());
    socket!.on('connect', (_) {
      debug('start() -- Connected', tag: debugTag);
    });
    socket!.onConnect((_) {
      debug('start() -- Connected', tag: debugTag);
    });
  }
`

I would appreciate any suggestion, comment or alternative. (I don't want to downgrade Node.js server version)

** I tried without setting transport, with only 'on' way, with only 'onConnect' way. None worked

**Comment by piyush101** [comment]
Try using flutter client : socket_io_client: ^2.0.0-beta.3-nullsafety.0.

**Comment by busslina** [comment]
> Try using flutter client : socket_io_client: ^2.0.0-beta.3-nullsafety.0.

Thank you very much. Now it works.

**Comment by thedarkknight197** [comment]
> Try using flutter client : socket_io_client: ^2.0.0-beta.3-nullsafety.0.

I have the same problem with express + typescript + nodejs!! Thank you for your answer, it resolve my problems ❤️

**Comment by vuthpov** [comment]
I'm new to flutter and using socket_io_client: ^2.0.0-beta.3-nullsafety.0. did not work for me. 
Here's my code:
![Untitled](https://user-images.githubusercontent.com/42206316/158121272-f8d69fbd-bff7-40c0-b18f-359f39a541ed.png)
This shows in the console:
![Untitled](https://user-images.githubusercontent.com/42206316/158121595-ece09311-4f48-455b-8e5e-4bee8909f41e.png)

**Comment by mohammedsafvan** [comment]
> socket_io_client: ^2.0.0-beta.3-nullsafety.0

check your IP address and replace the "localhost" with it
after that you may get an error on "version" so you should downgrade the version of socket_io_client in pubspec.yaml
I chose 1.0.1

`https://stackoverflow.com/questions/55785581/socketexception-os-error-connection-refused-errno-111-in-flutter-using-djan`

**Comment by vuthpov** [comment]
> > socket_io_client: ^2.0.0-beta.3-nullsafety.0
> 
> check your IP address and replace the "localhost" with it after that you may get an error on "version" so you should downgrade the version of socket_io_client in pubspec.yaml I chose 1.0.1
> 
> https://stackoverflow.com/questions/55785581/socketexception-os-error-connection-refused-errno-111-in-flutter-using-djan

Thanks for the advice. I replaced with IP address. Nothing shown, and when I removed the setTransports function, I got connection timeout shown in the console. The server serves HTML webpage which connect to socket.io and I can access to it just fine inside the emulator's browser.
