### ISSUE TITLE
No longer connecting to nodejs

### ISSUE THREAD

**Issue by Kavantix** [rikulo/socket.io-client-dart#26]
Dear Author,

Firstly, thanks for this package I have been using it over the past month and it has been working very well in my flutter app.

However, today I upgraded my libraries including this library from 0.9.1 to 0.9.3 and suddenly it won't connect to the node js websocket anymore.
After some testing I found out that when reverting to 0.9.1 everything still works but in 0.9.2 and 0.9.3 it doesn't anymore.

Not sure if this is important, but to get this library to work I had to set the transports to websocket only, for some reason polling and then upgrading was not working correctly (even though the web version of my app can use it).

**Comment by jumperchen** [comment]
0.9.2 has only with this fix - https://github.com/rikulo/socket.io-client-dart/issues/21
Could you verify whether the change make it unable to work with nodejs?

**Comment by Kavantix** [comment]
@jumperchen 0.9.2 does indeed still work (i also found that weird)
0.9.3 however does not. I managed to find that it thows an error that the headers map is a <dynamic, dynamic> map instead of <String, dynamic>
I made a pull request for it #27
