### ISSUE TITLE
dispose() and clearListeners() not working

### ISSUE THREAD

**Issue by ElegantSoft** [rikulo/socket.io-client-dart#267]
Hello, I am using socket.io and when user logout I call
```
  void logout() {
    debugPrint("will logout socket");
    chatSocket?.clearListeners();
    chatSocket?.dispose();
  }

```
I use websocketService class and use it with getIt 

```
class WebsocketService {
  // final Socket? socket;
  Socket? chatSocket;

  WebsocketService()
      : chatSocket =
            io("$Server/${SocketConstants.ChatNameSpace}", <String, dynamic>{
          'transports': <String>['websocket'],
          'query': <String, dynamic>{
            "access_token": token,
          }
        });

  void logout() {
    debugPrint("will logout socket");
    chatSocket?.clearListeners();
    chatSocket?.dispose();
  }

}


```

after calling logout function the app keeps handle sockets and doesn't clear listeners

**Comment by jumperchen** [comment]
which version are you using?

**Comment by ElegantSoft** [comment]
@jumperchen  The latest version
After debugging I found the issue was I create the connection 2 times so when I close connection it closes 1 connection.
you must handle that.

**Comment by ljmatan** [comment]
Please see https://github.com/rikulo/socket.io-client-dart/issues/258#issuecomment-1049585853

**Comment by hatemragab** [comment]
Any updates i faces the same in version 2.0.0

**Comment by iUngerTime** [comment]
For anyone looking at this, there is a flaw in the design of the baseline io command. See the comment below.

![image](https://github.com/rikulo/socket.io-client-dart/assets/52356657/66ad25fa-d4c5-4d42-9f5e-304487ccda04)

When logging out, even when you clear and dispose of the listeners and socket, the underlying library keeps a cache of the instance you connected to. So the other parts of your query are pretty much ignored.

You need to use the `.enableForceNew()` on the connect, as you can see below in my code, or clear the cache upon logout.

![image](https://github.com/rikulo/socket.io-client-dart/assets/52356657/8f4b4360-cc7b-4515-a953-44aacf00bfa2)

or

![image](https://github.com/rikulo/socket.io-client-dart/assets/52356657/e084ba34-6e60-4b15-890f-c3b3655b2ad3)

**Comment by PhantomKnight287** [comment]
> For anyone looking at this, there is a flaw in the design of the baseline io command. See the comment below.
> 
> ![image](https://private-user-images.githubusercontent.com/52356657/335860703-66ad25fa-d4c5-4d42-9f5e-304487ccda04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTgzNDksIm5iZiI6MTcxOTU5ODA0OSwicGF0aCI6Ii81MjM1NjY1Ny8zMzU4NjA3MDMtNjZhZDI1ZmEtZDRjNS00ZDQyLTlmNWUtMzA0NDg3Y2NkYTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE4MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4YWQwYTkwMzhkZTAwMWRjYzMyZDA2YTk4YTNlNzEzNzNkYWYyNjY4ZDAwZTg5MzJhNmUyMjA0MDhkYTY3YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ulY7J0ZOWTdLt6lexYagbBgi9jhs0muduYYj4yDooPI)
> 
> When logging out, even when you clear and dispose of the listeners and socket, the underlying library keeps a cache of the instance you connected to. So the other parts of your query are pretty much ignored.
> 
> You need to use the `.enableForceNew()` on the connect, as you can see below in my code, or clear the cache upon logout.
> 
> ![image](https://private-user-images.githubusercontent.com/52356657/335860957-8f4b4360-cc7b-4515-a953-44aacf00bfa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTgzNDksIm5iZiI6MTcxOTU5ODA0OSwicGF0aCI6Ii81MjM1NjY1Ny8zMzU4NjA5NTctOGY0YjQzNjAtY2M3Yi00NTE1LWE5NTMtNDRhYWNmMDBiZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE4MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMWM1NzhmOWFiZWU2NTBkMjM2ZjQ4MjY0NjJiM2UwZjg5MDdjM2U4YjU2OTFlMjNiZDA4ZDllNjVhMTI4OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vy-mbSL9HHegwGbuID3v4xPirlpGzPk4-584JIL-TEs)
> 
> or
> 
> ![image](https://private-user-images.githubusercontent.com/52356657/335860992-e084ba34-6e60-4b15-890f-c3b3655b2ad3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1OTgzNDksIm5iZiI6MTcxOTU5ODA0OSwicGF0aCI6Ii81MjM1NjY1Ny8zMzU4NjA5OTItZTA4NGJhMzQtNmU2MC00YjE1LTg5MGYtYzNiMzY1NWIyYWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDE4MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOTkzNDJkYTljYjk4NmI3ZjE5MTJiOWIwMDI5YTAyNDA3ODQxYzIyMzk4MzdmMDE1YjNiMDZhZGVmZGZjMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ipF0O4Xsel5Z-2jzlsSq2k7Po5Vi4FATkr7UyttZI9U)

You are a life saver, thank you for this response. My backend was getting same query params again and again on each connection causing weird behaviour. This fixes the issue
