### ISSUE TITLE
Unhandled Exception: Converting object to an encodable object failed: Closure: (dynamic) => Null

### ISSUE THREAD

**Issue by amirsuwal01** [rikulo/socket.io-client-dart#270]
The socket is connected successfully but got the error like the attachments. I am using the    socket_io_client: ^1.0.2.

This is how I connect the socket..
```
 Future<void> initSocket() async {
    try {
      socket = IO.io(
          SOCKET_URL,
          OptionBuilder()
              .setTransports(['websocket'])
              .disableAutoConnect()
              .build());
      socket.connect();
      socket.onConnect((_) => {
            socket.emit("initialize", {'id': '98989898'}),
            print("conect:${socket.id}")
          });
    } catch (e) {
      print('error==>${e.toString()}');
    }
  }
```

<img width="711" alt="Screen Shot 2022-04-25 at 10 37 19 PM" src="https://user-images.githubusercontent.com/92306783/165136426-3e6b81a2-b3e0-477f-90e7-4bbc7ee59df2.png">

**Comment by wupengbigMarker** [comment]
I got the error too

**Comment by rajeshbdabhi** [comment]
I got too

**Comment by ChiPhanTlm** [comment]
me too

**Comment by jumperchen** [comment]
Strange, I cannot get this error on my env. Perhaps you might run `pub upgrade` first.

**Comment by Ajay1lint** [comment]
i also got this error. i think it's valid Question.
