### ISSUE TITLE
Support of msgpack-parser

### ISSUE THREAD

**Issue by AndreiRoze** [rikulo/socket.io-client-dart#271]
Hi, on server i used `socket.io-msgpack-parser`, how can i parse data on client side? I know we haven't support of custom parser now, could you provide any ideas how can i do that. May be you can explain, where i need to change library's code?

**Comment by JedShiMing** [comment]
I have the same problem

**Comment by AndreiRoze** [comment]
@JedShiMing My solution is: 
1. Clone socket.io (https://github.com/rikulo/socket.io-client-dart) to project
2. Clone socket_io_common (https://github.com/rikulo/socket_io_common) to project
3. Add to `pubspec.yaml` msgpack (https://pub.dev/packages/msgpack_dart)
4. Edit `Encoder` and `Decoder` in `socket_io_common -> src -> parser -> parser.dart`

Example:
For my purpose new `encode` function in `Encoder` look like that: 
```
encode(obj, callback) {
    _logger.fine('encoding packet $obj');
    var enc = m2.serialize(obj);
    callback([enc]);
}
```
New `add` function in `Decoder` look like that:
  ```
add(obj) {
    var packet;

    // Parse type
    if (obj is String) {
        packet = <String, dynamic>{'type': num.parse(obj[8]), 'nsp': '/'};

        this.emit('decoded', packet);
    } else if (obj is Uint8List) {
        packet = m2.deserialize(obj);

        this.emit('decoded', packet);
    } else {
        throw UnsupportedError("Parser add error");
    }
}
```

P.s. m2 is `import 'package:msgpack_dart/msgpack_dart.dart' as m2;'`

**Comment by jumperchen** [comment]
Can be done with this feature #55
