### ISSUE TITLE
Socket.off is not working

### ISSUE THREAD

**Issue by glosama** [rikulo/socket.io-client-dart#273]
I connect my socket and start listening after emit,
`socket.emit('groupChat',{'data'}) `
`socket.on('message',(data){ print('$data') }`

Now its start listening every message from backend is working fine but I want to stop listening `socket.on('message')` so I tried `socket.off('message')` but after that its still receiving messages.

**Comment by jumperchen** [comment]
I try a simple case, and it works well.
