### ISSUE TITLE
how can we join in a channel ?

### ISSUE THREAD

**Issue by sergiotucano** [rikulo/socket.io-client-dart#277]
Hi ! 
I need join in a channel and listening then.
How I can do this with this component ?

For exemple.. in Java I do (with other component): 

```
SocketIOPrivateChannel privateChannel = echo.privateChannel("my_channel");
   privateChannel.listen("ChangeComponent", args -> {

      try {
          ...
      } catch (Exception e) {
          Timber.e("joined");
      }
  });

```

Thanks!

**Comment by hatemragab** [comment]
join a channel is called in socket io Rooms 
and this implementationis did on server-side
[https://socket.io/docs/v4/rooms/](Rooms)

**Comment by sleewok** [comment]
Just to clarify. Rather than joining a  channel from the client, the server joins a client to a channel/room server-side. Is that correct?
