### ISSUE TITLE
socket.on('event', (data) => ) is not working.

### ISSUE THREAD

**Issue by Saif-Hossain-Mredul** [rikulo/socket.io-client-dart#281]
I am facing issues. I am using node js as backend. Whenever I try to use 
`server.io.emit('recent-data', recentData);` 
the client is not getting any updates. 

But when I use `socket.emit` from server it works fine. 
`server.socket.emit('recent-data', recentData);`

my client code: 
```
socketio.emit('post-data', (data));
socketio.on('recent-data', (data) {
    print(data);
});
```

**Comment by trustratch** [comment]
I'm facing the same issue here in 1.0.2.  Our Socket.io version is still 2.x (due to some limitations).

**Comment by Saif-Hossain-Mredul** [comment]
> I'm facing the same issue here in 1.0.2. Our Socket.io version is still 2.x (due to some limitations).

Is the problem solved in version 2.x?

**Comment by trustratch** [comment]
Unfortunately, our socket.io version on the server side is 2.x. I tried using this library in version 2.0.0 but couldn't connect to the server since it's only compatible with socket.io version 3.x and above on the server side.

**Comment by trustratch** [comment]
Hi, @Saif-Hossain-Mredul  I figured that out that the root cause was from our server-side not the library itself. We're now able to receive messages from events correctly.
