### ISSUE TITLE
Error like this can't connect to server 

### ISSUE THREAD

**Issue by peterkuch** [rikulo/socket.io-client-dart#283]
<img width="758" alt="Screen Shot 2022-07-27 at 3 42 54 PM" src="https://user-images.githubusercontent.com/14107698/181203299-2fcf68b0-8235-4904-b7dd-752ea68961a5.png">
- Server i am using NodeJS

**Comment by jumperchen** [comment]
The url should be `http://192.168.33.29:3000`, more details, please refer to https://github.com/rikulo/socket.io-client-dart#connect-manually
