### ISSUE TITLE
Connection error on flutter web

### ISSUE THREAD

**Issue by Jamalianpour** [rikulo/socket.io-client-dart#286]
Hello,
I have a nodejs backend and try connecting with flutter web but on connection I got error:
```
{msg: websocket error, desc: null, type: TransportError}
```
But in android and desktop there isn't any error and all things work!

**Comment by fayfive** [comment]
I have the same problem
socket.io-client-dart version is 1.0.2
I have tried polling and websocket but still not work
Can the socket.io-client-dart run on the flutter web?

**Comment by fayfive** [comment]
I have solved.
It's CORS.

**Comment by Jamalianpour** [comment]
Just change `wss` to `https` and it was fixed.

**Comment by PatrikGolubar** [comment]
@fayfive What did you changed?

**Comment by PatrikGolubar** [comment]
@Jamalianpour 
Where to change wss to https?
