### ISSUE TITLE
reconnecting event is not triggered

### ISSUE THREAD

**Issue by may-comet** [rikulo/socket.io-client-dart#287]
When I turn off and then turn on wifi again, the socket is auto reconnect but the reconnecting event is not triggered. Can anyone fix this issue?

**Comment by pzehle** [comment]
I have the latest version and it is still not working. Are you guys sure this is fixed?

**Comment by marcusgregory** [comment]
I managed to use this stable version, I simply used setQuery({'',''}) and it worked, maybe in future versions, check if the map is null or empty before doing split operations
