### ISSUE TITLE
Question: Turn off/Turn on internet Socket create new connection instead of reusing the old one

### ISSUE THREAD

**Issue by un-hongly** [rikulo/socket.io-client-dart#288]
Hi,
I faced a use case where users turn off their internet and then turn it on again. What I expect is the socket client to reconnect and reuse the old connection but instead, it creates a new connection (with new socketId) and disconnects the old one.

**Comment by jumperchen** [comment]
do you have any simple example to reproduce this issue?

**Comment by un-hongly** [comment]
> do you have any simple example to reproduce this issue?
My problem is solved. It's ok to have different socketId on each reconnection. By tweaking pingTimeout at server side and reconnectionDelay(bigger than pingTimeout) at client side I managed to get the server realized the disconnect of client side before new connection established.

Before:
New connection connected
Old connection disconnected

Now:
Old connection disconnected
New connection connected
