### ISSUE TITLE
socket.onDisconnect listener not Working in [IOS]

### ISSUE THREAD

**Issue by mmustafaget** [rikulo/socket.io-client-dart#290]
```
socket = IO.io(
        '${ServerURLs.socketURL}',
        IO.OptionBuilder()
            .setTransports(['websocket'])
            .disableAutoConnect()
            // .enableForceNewConnection()
            // .enableReconnection()
            // .setReconnectionDelay(5000)
            // .enableForceNew()
            .build(),
      );
```

```
socket.onDisconnect((data) {
      debugPrint('Socket ========== isSocketDisconnect: ${socket.connected}');
     
    });
```
Above event is not listener in IOS when we Turn oFF the WIFI and turn it on Again.

Android => When we turn off the WIFI we fall on this event => socket.onDisconnect() 
IOS.       => When we turn off the WIFI we didn't fall on this event => socket.onDisconnect() 

**Socket Version:**
socket_io_client: ^2.0.0

**Comment by 2kjm** [comment]
Any updates on this? I am facing the same issue.

**Comment by mmustafaget** [comment]
> Any updates on this? I am facing the same issue.

When we turn off the WiFi on an Android device, it takes approximately 45 seconds for the socket to disconnect. Similarly, on iOS devices, it takes around 25 to 30 seconds for the socket to disconnect after the WiFi is turned off.

**Comment by 2kjm** [comment]
@mmustafaget  Yeah, I am facing it too.  But for me, it's only on iOS

**Comment by rmasarovic** [comment]
same issue here

**Comment by mmustafaget** [comment]
> > @mmustafaget Yeah, I am facing it too. But for me, it's only on iOS
> 
> wait and check disconnect call after some delay

@rmasarovic
