### ISSUE TITLE
getting null when calling emit function.

### ISSUE THREAD

**Issue by mohd-afid** [rikulo/socket.io-client-dart#297]
var RouterRtpCapabilities  = _webSocket!.socket.emit(['getRouterRtpCapabilities']);
print(RouterRtpCapabilities  ); 
// iam getting null on this value

**Comment by jumperchen** [comment]
https://github.com/rikulo/socket.io-client-dart/blob/903509120be5b398faa0508f543be30a74c8b2c3/lib/src/socket.dart#L122

The `emit()` function doesn't return any value, so do you want a callback function (i.e. `ack`) like this ? - https://github.com/rikulo/socket.io-client-dart/blob/903509120be5b398faa0508f543be30a74c8b2c3/lib/src/socket.dart#L135
