### ISSUE TITLE
The library cannot switch between long polling and websocket

### ISSUE THREAD

**Issue by lopezchr** [rikulo/socket.io-client-dart#32]
The library only works when you use transporting over websocket. By default the library send the connection request over http (long polling) and you can see it on the access log of the server but never switch to websocket.

We are using socket io version 2.0.4 on our server.

`172.31.3.14 - - [20/Aug/2019:08:12:06 -0500] "GET /socket.io/?EIO=3&transport=polling&t=Mol9v3G&sid=c40FSVz-gs98xm1iAALE HTTP/1.1" 200 3 "http://stagingiris.1doc3.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36" "201.217.201.157"`

**Comment by jumperchen** [comment]
It works to me.
socket.io 2.0.4 version `NodeJS`

![Screen Shot 2019-08-21 at 10 42 10 AM](https://user-images.githubusercontent.com/201100/63398507-70060e80-c400-11e9-84d8-8d77f48e5ccb.png)

### Server code
```
const io = require('socket.io')(3000);
io.origins('*:*');
io.on('connection', function (socket) {
    socket.on('msg', (data) => {
        console.log('data from default => ' + data);
      socket.emit('fromServer', data);
    });
});
```

### Socket.io-client-dart
```
import 'package:socket_io_client/socket_io_client.dart' as IO;

main() {
  IO.Socket socket = IO.io('http://localhost:3000');
  socket.on('connect', (_) {
    print('connect');
    socket.emit('msg', 'init');
    int count = 0;
    new Timer.periodic(const Duration(seconds: 1), (Timer countDownTimer) {
      socket.emit('msg', count++);
    });
  });
  socket.on('fromServer', (_) => print(_));
}
```

**Comment by lopezchr** [comment]
We are working on a Flutter app... maybe is not supported??

**Comment by jumperchen** [comment]
Flutter? it's not browser based, you can only use `dart:io` library, which is already mentioned here. https://github.com/rikulo/socket.io-client-dart/blob/master/test/io_client.dart
