### ISSUE TITLE
socket.on('receiveMessage',(data)=>print("data")) called twice

### ISSUE THREAD

**Issue by jabonge** [rikulo/socket.io-client-dart#33]
socket = IO.io("myserverurl", <String, dynamic>{
          'transports': ['websocket']
        });
        socket.nsp = "/chats";

        socket.on("receiveMessage", (data) {
          print("from socket $data");
                 });
        socket.connect();
        socket.emit("join", {"Id": "id"});

i send message my server  log message call twice why it is called twice?
server code 
io.of('nsp').to('id').('receiveMessage',message);

**Comment by jabonge** [comment]
in Flutter i dont really know why log called twice i will wait answer thank you for your attention

**Comment by bastibense** [comment]
Came across the same issue. Apparently calling `.connect()` causes all event handlers to get registered/fired twice.

Try removing the `connect()` call, the socket should automatically connect.

**Comment by leonidl** [comment]
You can also add "'autoConnect': false" option to optional parameters list to stop socket from auto-connecting. In that case you will have to call connect() manually.

**Comment by bastibense** [comment]
Still, shouldn't this at least print out a warning to the log or just ignore a second call to connect()?

**Comment by jumperchen** [comment]
@bastibense I reopen it, and it looks like the behavior is not the same as JS version.

**Comment by itaispector** [comment]
> Came across the same issue. Apparently calling `.connect()` causes all event handlers to get registered/fired twice.
> 
> Try removing the `connect()` call, the socket should automatically connect.

still fired twice

**Comment by RIddhiIroid** [comment]
> > Came across the same issue. Apparently calling `.connect()` causes all event handlers to get registered/fired twice.
> > Try removing the `connect()` call, the socket should automatically connect.
> 
> still fired twice

Hello
Did you manage to solve this?

**Comment by akshayindia** [comment]
Facing the same issue flutter...

**Comment by akshayindia** [comment]
front end ---- 

IO.Socket? socket;
  @override
  void initState() {
    super.initState();
    // connect();

    focusNode.addListener(() {
      if (focusNode.hasFocus) {
        setState(() {
          show = false;
        });
      }
    });
    connect();
  }

  void connect() {
    // MessageModel messageModel = MessageModel(sourceId: widget.sourceChat.id.toString(),targetId: );
    socket = IO.io("https://studiovity.com/", <String, dynamic>{
      "transports": ["websocket"],
      // "autoConnect": true,
    });
    // socket!.connect();
    socket!.emit("signin", widget.sourchat.id);
    socket!.onConnect((data) {
      print("Connected");
      socket!.on("message", (msg) {
        print(msg);
        setMessage("destination", msg["message"]);
        _scrollController.animateTo(_scrollController.position.maxScrollExtent,
            duration: Duration(milliseconds: 300), curve: Curves.easeOut);
      });
    });
    print(socket!.connected);
  }

Backend 

const express = require("express");
var http = require("http");
const app = express();
const port = process.env.PORT || 5000;
var server = http.createServer(app);
var io = require("socket.io")(server);

//middlewre
app.use(express.json());
var clients = {};

io.on("connection", (socket) => {
  console.log("connetetd");
  // accept();
  console.log(socket.id, "has joined");
  socket.on("signin", (id) => {
    console.log(id);
    clients[id] = socket;
    console.log(clients);
  });
  socket.on("message", (msg) => {
    console.log(msg);
    let targetId = msg.targetId;
    if (clients[targetId]) clients[targetId].emit("message", msg);
  });
});

server.listen(port, "0.0.0.0", () => {
  console.log("server started");
});

**Comment by Nandan-Wewhare** [comment]
Any updates on this?
