### ISSUE TITLE
Add support for extraHeaders

### ISSUE THREAD

**Issue by theochampion** [rikulo/socket.io-client-dart#34]
I'm trying to do authentication via passport using this https://github.com/jfromaniello/passport.socketio but it require authentication cookie to be passed as a header.

I think this is a pretty common usecase and only supporting query params isn't fit for everything.

Would it be possible to add support for headers (just like `extraHeaders` in the js client lib https://socket.io/docs/client-api/#With-extraHeaders)

Happy to help if needed :)

Cheers

**Comment by jumperchen** [comment]
As this comment - https://github.com/rikulo/socket.io-client-dart/issues/30#issuecomment-518058191
Welcome to contribute, if you would like to. :)

**Comment by jumperchen** [comment]
@theochampion Please help me to test it if it works, thanks.
