### ISSUE TITLE
unable to connect to the socket server

### ISSUE THREAD

**Issue by albatomuch** [rikulo/socket.io-client-dart#344]
i am unable to connect to the socket server using typescript (socket.io: 4.7.2) and the flutter app using (socket_io_client:1.0.0) with the error 'ping timeout' however, upon testing the same on postman, everything works just fine. 
any assistance will be appreciated!

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#version-info

**Comment by albatomuch** [comment]
when i use  any v2, the socket server is not detected at all.

**Comment by jumperchen** [comment]
To work with socket.io dart client, you have to know which application type you are using, such as Flutter app, Flutter Web app, Pure Dart Client app, or Pure Dart app. Each different type requires a different connecting argument, which you can find in the README.md file in the repo. Even if the connecting arguments are correct, you have to setup the http server config (such as Apache HTTP server or Nginx) to make it work with socket.io connection, such as WebSocket, or pure HTTP connection.
The pure test code can work in the pure Dart app or pure Dart client app, please take a look at [Dart client](https://github.com/rikulo/socket.io-client-dart/blob/master/test/io_client.dart) to access [NodeJs server](https://github.com/rikulo/socket.io-client-dart/blob/master/test_nodejs/server.js) and this [Flutter example](https://gist.github.com/jumperchen/037a180c8d08a6e795b34eee65ed8ef3) can work too.

**Comment by albatomuch** [comment]
what would be the ideal setup if I am using using socket_io_client on flutter app and now shifted to pure dart for server side using socket_io 1.0.1. I am still getting the same error message `[ping timeout, null]` .
