### ISSUE TITLE
does not connect to a minimal socket io node js server

### ISSUE THREAD

**Issue by boussarilatif** [rikulo/socket.io-client-dart#35]
import 'package:socket_io/socket_io.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;

main() {
    
    IO.Socket socket = IO.io('http://localhost:8000');
    socket.on('connect', (_) {
     print('connect');
     socket.emit('msg', 'test');
    });
    socket.on('event', (data) => print(data));
    socket.on('disconnect', (_) => print('disconnect'));
    socket.on('fromServer', (_) => print(_));
}

//node js server
const io = require("socket.io"),
  server = io.listen(8000);

let sequenceNumberByClient = new Map();

server.on("connection", socket => {
  console.info(`Client connected [id=${socket.id}]`);

  sequenceNumberByClient.set(socket, 1);

 
  socket.on("disconnect", () => {
    sequenceNumberByClient.delete(socket);
    console.info(`Client gone [id=${socket.id}]`);
  });
});

**Comment by everton-e26** [comment]
maybe you need add trasport option when creating socket instance

```dart
socket = IO.io('http://localhost:8000', <String, dynamic>{
        'transports': ['websocket'],
      });
```

worked for me
