### ISSUE TITLE
Unexpected List Type for 'status' Event with Connection State Recovery Enabled

### ISSUE THREAD

**Issue by kryptamine** [rikulo/socket.io-client-dart#359]
### Steps to Reproduce:

1. Enable [connection state recovery](https://socket.io/docs/v4/connection-state-recovery) feature.
2. Emit a  'status' event with a string value from the server using `socket.emit('status', 'waiting')`.
3. Subscribe to the 'status' event on the client using the provided Dart library 
```dart
   socket.on('status', (data) {
        ....
   }).
```
4. Observe that the data parameter is of type List with two elements instead of the expected string.

### Expected Behavior:
The 'status' event should deliver a string as the data parameter, as it does when connection state recovery is disabled.

### Actual Behavior:
The 'status' event delivers a List with two elements (pid and string)

### Environment:
Socket.IO client Dart library version: 2.0.3
Connection state recovery settings: 
```
  connectionStateRecovery: {
    maxDisconnectionDuration: 2 * 60 * 1000,
    skipMiddlewares: true,
  },
```

### Screenshots:
Connection state recovery  disabled:

<img width="576" alt="image" src="https://github.com/rikulo/socket.io-client-dart/assets/7682795/4c6184f8-11cf-4279-902f-86b892ec5d51">

Connection state recovery  enabled:

<img width="542" alt="image" src="https://github.com/rikulo/socket.io-client-dart/assets/7682795/4088d3f2-a18f-492b-ba75-e3e01e024264">

**Comment by jumperchen** [comment]
After tested on Socket.io client (JS), it received the extra data as well.
So, this could be like a Socket.io server's bug, because it will send an unique id at the end of the arguments when enabled connection state recovery.
