### ISSUE TITLE
Event listeners not being fired on iOS

### ISSUE THREAD

**Issue by Tbrz423** [rikulo/socket.io-client-dart#36]
I've setup a SocketIO client in my Flutter project, and can successfully connect to a local SocketIO server. The connect and disconnect events work, and I am able to emit data to the server, however when the server emits data the client's events don't fire.

Code for client:

   ```
IO.Socket socket = IO.io('http://127.0.0.1:5000', <String, dynamic>{
      'transports': ['websocket']
    });

    socket.on('connect', (_) {
     print('connected');
     socket.emit('message', {'message': 'hello'});
    });

    socket.on('message', (data) {
      print(data);
    });

    socket.on('disconnect', (_) => print('disconnect'));
```

The server is written in Python using Flask-SocketIO, and I know the implementation is correct as it can communicate fine with Python and C# SocketIO programs.

Flutter version: 1.9.1+hotfix.4
socket_io_client version: ^0.9.4

I suspected this might have been a firewall problem however I was able to run a similar Python SocketIO server and send and receive messages on the same computer.
Any help is appreciated.

**Comment by jumperchen** [comment]
Please try with the latest version to see if it helps.

**Comment by larsbs** [comment]
Just tried it, the issue still persists.

**Comment by jumperchen** [comment]
@larsbs I try the following example with iPhone 11 simulator on Android Studio, it works well.
Here is my env. version:
* NodeJs Socket.io server: `2.3.0`
* Flutter `1.12.13+hotfix.7`
* Dart `2.7.0`
* socket_io_client `0.9.8`

The example,
```
void initState() {
    super.initState();
    _socket = IO.io('http://MyIPAddress:3000', <String, dynamic>{'transports': ['websocket']});
    _socket.connect();
    print('test');
    _socket.on("connect", (_) {
      print('Connected');
      _socket.emit('toServer', json.encode({'key': 'hello', 'value': 'world'}));
    });
    _socket.on("fromServer", (_) {
      print('fromServer $_');
    });
    _socket.on("connect_error", (data) => print('connect_error: ' + data));

    super.initState();
  }
```

Socket.io server (both NodeJs `2.3.0` and Dart version are okay)
```
var http = require('http').createServer();
var io = require('socket.io')(http);

io.on('connection', (client) => {
    console.log('a user connected')

    client.on('toServer', (data) => {
        console.log('Message received --> ', data)
        client.emit('fromServer', 'fromServer -> ' + data);
    })
})

http.listen(3000, function(){
    console.log('listening on *:3000');
});
```
The result printed on Android Studio:
```
Performing hot restart...
Syncing files to device iPhone 11 Pro Max...
Restarted application in 1,712ms.
flutter: test
flutter: build
flutter: Connected
flutter: fromServer fromServer -> {"key":"hello","value":"world"}
```

**Comment by tazik561** [comment]
socker server that i use , using https and implemented with c# . your code have not difference to my code and i still can not able to connect to server.

**Comment by larsbs** [comment]
Confirmed to be working. I wasn't specifying the transport protocol.

**Comment by jumperchen** [comment]
@Tbrz423 I try with the [python server example](https://python-socketio.readthedocs.io/en/latest/intro.html#server-examples), and the code above I post still works well on Android Studio in either iOS or Android simulator, so I close this issue.

**Comment by e200** [comment]
> @larsbs I try the following example with iPhone 11 simulator on Android Studio, it works well.
> Here is my env. version:
> 
>     * NodeJs Socket.io server: `2.3.0`
> 
>     * Flutter `1.12.13+hotfix.7`
> 
>     * Dart `2.7.0`
> 
>     * socket_io_client `0.9.8`
> 
> 
> The example,
> 
> ```
> void initState() {
>     super.initState();
>     _socket = IO.io('http://MyIPAddress:3000', <String, dynamic>{'transports': ['websocket']});
>     print('test');
>     _socket.on("connect", (_) {
>       print('Connected');
>       _socket.emit('toServer', json.encode({'key': 'hello', 'value': 'world'}));
>     });
>     _socket.on("fromServer", (_) {
>       print('fromServer $_');
>     });
>     _socket.on("connect_error", (data) => print('connect_error: ' + data));
> 
>   }
> ```
> 
> Socket.io server (both NodeJs `2.3.0` and Dart version are okay)
> 
> ```
> var http = require('http').createServer();
> var io = require('socket.io')(http);
> 
> io.on('connection', (client) => {
>     console.log('a user connected')
> 
>     client.on('toServer', (data) => {
>         console.log('Message received --> ', data)
>         client.emit('fromServer', 'fromServer -> ' + data);
>     })
> })
> 
> http.listen(3000, function(){
>     console.log('listening on *:3000');
> });
> ```
> 
> The result printed on Android Studio:
> 
> ```
> Performing hot restart...
> Syncing files to device iPhone 11 Pro Max...
> Restarted application in 1,712ms.
> flutter: test
> flutter: build
> flutter: Connected
> flutter: fromServer fromServer -> {"key":"hello","value":"world"}
> ```

I tried the exactly same event and it's not working...
