### ISSUE TITLE
Error on dispose

### ISSUE THREAD

**Issue by afl-h** [rikulo/socket.io-client-dart#367]
Describe the bug
The following _TypeError was thrown while finalizing the widget tree:
type 'String' is not a subtype of type 'int' of 'index'

When the exception was thrown, this was the stack:
#0 Manager.onclose (package:socket_io_client/src/manager.dart:385:32)
https://github.com/flutter-webrtc/flutter-webrtc/issues/1 Manager.disconnect (package:socket_io_client/src/manager.dart:370:5)
https://github.com/flutter-webrtc/flutter-webrtc/issues/2 Manager.close (package:socket_io_client/src/manager.dart:364:19)
https://github.com/flutter-webrtc/flutter-webrtc/issues/3 Manager.destroy (package:socket_io_client/src/manager.dart:323:5)
https://github.com/flutter-webrtc/flutter-webrtc/issues/4 Socket.destroy (package:socket_io_client/src/socket.dart:572:8)

To Reproduce
When calling socket.dispose() or socket.destroy()

Platform information

Flutter version: Flutter 3.19
Plugin version: ^0.9.48+hotfix.1
OS: Android / iOS/Desktop

**Comment by BrianMwas** [comment]
I am getting this issue even in the version beta release

**Comment by jumperchen** [comment]
> I am getting this issue even in the version beta release

Did you use `3.0.0-beta.1`?

**Comment by BrianMwas** [comment]
I tried using that but it requires js 0.7 but my other libs are using js 0.6

**Comment by jumperchen** [comment]
My mistake, what I meant is the latest beta version '3.0.0-beta.2'.
