### ISSUE TITLE
js version is too high. Many popular libraries depend on 0.6.x. Version is incompatible.

### ISSUE THREAD

**Issue by kjxbyz** [rikulo/socket.io-client-dart#371]
js version is too high. Many popular libraries depend on 0.6.x. Version is incompatible.

**Comment by jumperchen** [comment]
Thank you for bringing this to our attention. We understand that many popular libraries rely on version 0.6.x, and compatibility is a key concern. We are exploring ways to address this, including the possibility of supporting multiple versions or finding a workaround that maintains compatibility with the wider ecosystem. In the meantime, we welcome any suggestions or contributions from the community that could help resolve this issue.

**Comment by kjxbyz** [comment]
Thank you for your reply. This issue is quite urgent. Version 2.x is not compatible with my socket server version. I created a new flutter project and after testing, the 3.x version works fine, but because of this issue, I cannot upgrade to the 3.x version.

**Comment by jumperchen** [comment]
Ok, I found there is no usage in the current 3.0 version, so I will remove the js package dependency in v3.0.0-beta.2.
Hope this can help you. :)

**Comment by kjxbyz** [comment]
Thank you.
