### ISSUE TITLE
WebSocketException: Connection to 'APIURL:0/socket.io/?EIO=4&transport=websocket#' was not upgraded to websocket

### ISSUE THREAD

**Issue by talha-veroke** [rikulo/socket.io-client-dart#377]
Having this issue, While using this package. 

`IO.Socket socket = IO.io(
    APIConfiguration.SocketUrl,
    OptionBuilder()
        .setTransports(['websocket'])
        .disableAutoConnect()
        .setReconnectionAttempts(2)
        .setExtraHeaders({
          'access_token': await StorageService().readString(Keys.Auth_Token),
        })
        .build(),
  );
  socket.connect();
  socket.onConnect((data) => print('connected'));
  socket.onConnectError((data) => print('error $data'));`

**Comment by Abdulah-butt** [comment]
getting same issue. Did you get it?

**Comment by LeandreBl** [comment]
I have the same problem:
I'm not using any proxy/reverse proxy, just bare websockets
JS code:
```js
const io = require("socket.io")();
io.on("connection", (client) => {
  console.log(client);
});
io.listen(8080);
```

Flutter code:
```dart
socket = io.io('http://192.168.1.21:8080/');

socket.on('connect', (_) {
 // Log connected
});
```

Flutter socket.io version: 3.0.0-beta.2
Node socket.io version: 4.7.5

The package sends an http request such as:
```
GET /socket.io/?EIO=4&transport=polling HTTP/1.1
user-agent: Dart/3.3 (dart:io)
connection: Upgrade
cache-control: no-cache
accept-encoding: gzip
sec-websocket-version: 13
host: 192.168.1.21:8080
sec-websocket-extensions: permessage-deflate; client_max_window_bits
sec-websocket-key: /sw+T3olAOIhxjIAtxIdcg==
upgrade: websocket
```

While a simple curl working request is just:
```
GET /socket.io/?EIO=4&transport=polling HTTP/1.1
Host: 192.168.1.21:8080
User-Agent: curl/7.81.0
Accept: */*
```

**Comment by LeandreBl** [comment]
If you really want to access "APIURL:0/socket.io/?EIO=4&transport=websocket#", then you have a problem somewhere, as "0" is not a valid port, it might be the problem here.

**Comment by ROD-MASAMI** [comment]
i have the same problem i used my server_Url without specifiying any port but the package appended the ':0/socket.io/' how do i remove that i tried specifying the port in my url but it doesnt change

**Comment by talha-veroke** [comment]
My issue was resolved, it was some configuration issue on server side and our devops team resolved it.
