### ISSUE TITLE
Improve pub.dev score

### ISSUE THREAD

**Issue by Vardiak** [rikulo/socket.io-client-dart#38]
I feel that this repository should be more popular and be the de facto solution when building a socket.io application in dart, especially with Flutter.

Because of this issue, other repositories that are only an abstraction over socket.io-java and socket.io-swift are gaining more traction even though this package should be used instead.

I think it is explained by the bad scoring of this package on pub.dev which impact a lot on search ranking ([link here](https://pub.dev/packages/socket_io_client#-analysis-tab-)). We should do something about it, because I feel that this package is really well made.

**Comment by jumperchen** [comment]
Yes, it's welcome to contribute it, if you would like to. :)

**Comment by jumperchen** [comment]
Now it got 95 score. :)
