### ISSUE TITLE
This says 'client', what if i want my server in dart? anything i should be looking into?

### ISSUE THREAD

**Issue by danielAsaboro** [rikulo/socket.io-client-dart#383]

**Comment by danielAsaboro** [comment]
why not? i would be more than happy to contribute.
how do I get started?

**Comment by jumperchen** [comment]
Checkout Socket.io JS server source code, and then convert its source code one by one from JavaScript to Dart lang. :)

**Comment by danielAsaboro** [comment]
am i safe to assume the parser in socket commons is what's used on the server too?

**Comment by jumperchen** [comment]
> am i safe to assume the parser in socket commons is what's used on the server too?

Yes, it should be the same.
