### ISSUE TITLE
 Bug in Example Code – Missing Parameter in addResponse Usage on pub.dev

### ISSUE THREAD

**Issue by anayaher** [rikulo/socket.io-client-dart#396]
There seems to be a bug in the example code provided on the official pub.dev page for the package. Specifically, in the setup of the StreamSocket class, the getter addResponse is supposed to add a String to the stream, but it’s not correctly utilized when handling socket events.

This can lead to confusion for developers trying to implement this pattern following the example.

### Steps to Reproduce:
Take the code from the pub.dev example:

```
socket.on('event', (data) => streamSocket.addResponse);
```

In this line, the addResponse function is referenced, but the event data is never passed to it.

This results in no data being added to the stream, which prevents event handling in the StreamBuilder widget.

### Suggested Fix:
Modify the example code to pass the event data like this:

```
socket.on('event', (data) => streamSocket.addResponse(data));
```
This will ensure that the event data is correctly added to the stream for use in StreamBuilder.

### Additional Information:
Since this is part of the official example, fixing this will help avoid confusion and ensure that developers can implement it correctly. I can also contribute a pull request if needed.

**Comment by anayaher** [comment]
Need to make same change in the Main Readme.md to see the change on the pub.dev

**Comment by jumperchen** [comment]
It needs to release a new version to update, so please wait for next release version.
