### ISSUE TITLE
socket driver versions???? 

### ISSUE THREAD

**Issue by albinrk10** [rikulo/socket.io-client-dart#400]
In this version of socket_io_client 3.0.2
can I use v2 or is it only for v3 ???

why do i get this error when i try to connect to a socket v2

[log] Error de conexión: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)

**Comment by jumperchen** [comment]
Please refer to https://github.com/rikulo/socket.io-client-dart?tab=readme-ov-file#version-info
