### ISSUE TITLE
 'transports': ['polling','websocket'] cant work

### ISSUE THREAD

**Issue by HnLong** [rikulo/socket.io-client-dart#41]
Hi guys:
in my client as below:

import 'dart:async';
import 'package:socket_io_client/socket_io_client.dart' as IO;

main() {
  IO.Socket socket = IO.io('http://127.0.0.1:8090/xy', <String, dynamic>{
    'transports': ['polling','websocket'],
    'extraHeaders': {'foo': 'bar'}
  });
  socket.on('connect', (_) {
    print('socket_io_client===>connect http://127.0.0.1:8090/xy');
    socket.emit('msg', 'init');
    int count = 0;
    new Timer.periodic(const Duration(seconds: 20), (Timer countDownTimer) {
      socket.emit('msg', count++);
    });
  });
  socket.on('event', (data) => print(data));
  socket.on('disconnect', (_) => print('disconnect http://127.0.0.1:8090/xy'));
  socket.on('fromServer', (_) => print(_));
}

pubspec.yaml
#socketIO 
  socket_io_common: ^0.9.0+5
  socket_io_client:
    git:
      url: https://github.com/rikulo/socket.io-client-dart 

and my socket  server version is  "socket.io": "2.0.4"(also try with "2.3.0") on the nodejs server.
now issue: the client  cant conn to the server. but if transports replace with  'transports': ['websocket'],it work ok.so how to fix it in my project? thx very much!

**Comment by jumperchen** [comment]
Are you using it in Flutter env.? if so, there is no `dart:html` api available in Flutter, so it can only work with `websocket` transports.

**Comment by HnLong** [comment]
sure in Flutter env. yeh the README.md has explain that,I was careless.thanks chen!
