### ISSUE TITLE
[Discussion] Make this library more "Darty"

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [rikulo/socket.io-client-dart#46]
Is it more important to stay true to the JavaScript style of the library or should this port take into account the standard Dart style which is less error-prone than checking `String`s? For example ,

```dart
socket.on('connect', (_) {});
```
would be
```dart
socket.onConnect((_) {});
```
etc

**Comment by jumperchen** [comment]
Yes, agree with that, we could make a high level API to forward it to the original API.

**Comment by qiwang97** [comment]
Maybe we can  take advantage of `stream `

**Comment by Ascenio** [comment]
I like the idea. For now we could redirect the `.on` calls to their corresponding `.onSomething()`, while tagging the former as deprecated.

**Comment by jodinathan** [comment]
Our company has a need to make DataChannel messages ackable, we are pondering in adding DataChannel as a transport in this package.
If we are going to do it, we may also add pedantic analaysis_options, fix the lints, try to remove the use of Maps and add some streams to events (as a high level api).

What do you think?

> I like the idea. For now we could redirect the `.on` calls to their corresponding `.onSomething()`, while tagging the former as deprecated.

How would you deprecate ```on('disconnect')``` but not ```on('myCustomCommand')``` ?

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart#usage-with-stream-and-streambuilder-in-flutter
And could integrate with https://dart.dev/guides/language/extension-methods for the socket object.

**Comment by bpilot** [comment]
I am grateful this client exists.

If you replace the opts object (which is a Dart map at the moment) with a class with properly typed fields, that would make the library easier to use in my opinion.

Cheers

**Comment by jumperchen** [comment]
@bpilot we could consider to use Builder Pattern for the opts object without changing existing code.
