### ISSUE TITLE
Socket not working in my project

### ISSUE THREAD

**Issue by prabhunath111** [rikulo/socket.io-client-dart#49]
Can anyone provide steps by which I can implement a socket in my project?

When I am cloning this project it's working fine but I would like to use socket in my own project and i am facing issues with connecting the socket, Actually, I am not getting how to use socket exactly.

**Comment by poumason** [comment]
do your project have namespace?
I try my project such as https://localhost/channel, the socketClient always can't connect

**Comment by prabhunath111** [comment]
> do your project have namespace?
> I try my project such as https://localhost/channel, the socketClient always can't connect

Now it's connecting but i am not able to receive message from socket, emmit method working fine but whenver on method calls application crashes. Can you help please?

**Comment by jumperchen** [comment]
@prabhunath111 Which env. in your project are you using? Flutter or Dart.
It's useful if you can show some code here.

**Comment by prabhunath111** [comment]
Now i have a plugin which is working fine , thanks a lot for support
