### ISSUE TITLE
extraHeaders parameter is ignored in Flutter Web

### ISSUE THREAD

**Issue by leonidl** [rikulo/socket.io-client-dart#52]
When connecting to a socket with extraHeaders parameter it is ignored in Flutter Web. The parameter is used fine in iOS and Andriod. Specificlly, the parameter I used i "Authorization" to pass the token at the time of establishing the connection.

**Comment by jumperchen** [comment]
It may be related - https://github.com/socketio/socket.io-client/blob/master/docs/API.md#with-extraheaders
If you use Flutter-Web, you can use polling transport instead.
