### ISSUE TITLE
Flutter Example is needed

### ISSUE THREAD

**Issue by aliyazdi75** [rikulo/socket.io-client-dart#54]
I'm so confused how to use this in flutter.
I have a state class and use this in initState:
`    _socket = IO.io(SERVER, <String, dynamic>{
      'transports': ['websocket'],
    });
    _socket.emit(EMIT, _emitData);
    _socket.on(MESSAGE_RSV, (message) {
      if (mounted) {
        setState(() {
          print(message['message']);
        });
      }
    });`
then if I close this state and then reopen it:
`    _socket.on(MESSAGE_RSV, (message) {
      if (mounted) {
        setState(() {
          print(message['message']);
        });
      }
    });` 
doesn't work!
Is destroy needed in dispose state?
I used connect function but `soket.on` called twice.
Is there a strong Flutter example?

**Comment by jumperchen** [comment]
Here is the simple example with StatefulWidget.
```
import 'package:flutter/material.dart';
import 'package:socket_io_client/socket_io_client.dart' as IO;


void main(){
  runApp(
      new MaterialApp(
        title: 'Hello World App',
        home: new MyApp(),
      )
  );
}

class MyApp extends StatefulWidget {
  @override
  _State createState() => new _State();
}

class _State extends State<MyApp>{
  @override
  Widget build(BuildContext context) {
    IO.Socket socket = IO.io('http://MyIP:3000', <String, dynamic>{'transports': ['websocket']});
    socket.on('connect', (_) {
      print('connect');
      socket.emitWithAck('msg', 'init', ack: (data) {
        print('ack $data') ;
        if (data != null) {
          print('from server $data');
        } else {
          print("Null") ;
        }
      }, binary: false);
    });
    socket.on('disconnect', (_) => print('disconnect'));
    
    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Welcome to Flutter'),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```

And then the console will print them as follows.
```
I/flutter ( 8708): connect
I/flutter ( 8708): ack init
I/flutter ( 8708): from server init
```

**Comment by ad-on-is** [comment]
> Here is the simple example with StatefulWidget.
> 
> ```
> import 'package:flutter/material.dart';
> import 'package:socket_io_client/socket_io_client.dart' as IO;
> 
> 
> void main(){
>   runApp(
>       new MaterialApp(
>         title: 'Hello World App',
>         home: new MyApp(),
>       )
>   );
> }
> 
> class MyApp extends StatefulWidget {
>   @override
>   _State createState() => new _State();
> }
> 
> class _State extends State<MyApp>{
>   @override
>   Widget build(BuildContext context) {
>     IO.Socket socket = IO.io('http://MyIP:3000', <String, dynamic>{'transports': ['websocket']});
>     socket.on('connect', (_) {
>       print('connect');
>       socket.emitWithAck('msg', 'init', ack: (data) {
>         print('ack $data') ;
>         if (data != null) {
>           print('from server $data');
>         } else {
>           print("Null") ;
>         }
>       }, binary: false);
>     });
>     socket.on('disconnect', (_) => print('disconnect'));
>     
>     return MaterialApp(
>       title: 'Welcome to Flutter',
>       home: Scaffold(
>         appBar: AppBar(
>           title: Text('Welcome to Flutter'),
>         ),
>         body: Center(
>           child: Text('Hello World'),
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> And then the console will print them as follows.
> 
> ```
> I/flutter ( 8708): connect
> I/flutter ( 8708): ack init
> I/flutter ( 8708): from server init
> ```

Sorry, but how is this an example, if you don't show a way of putting the socketio data into the Text-widget?

**Comment by jumperchen** [comment]
@ad-on-is  you can use **setState()** to change the variable which is bound to the text widget.
For example:

```
class _State extends State<MyApp>{
  String _textFromServer = "";
  IO.Socket _socket;

  @override
  void initState() {
    super.initState();
    _socket = IO.io('http://MyIP:3000', <String, dynamic>{'transports': ['websocket']});
    _socket.on('connect', (_) {
      print('connect');
      _socket.emitWithAck('msg', 'init', ack: (data) {
        print('server: $data');
        setState(() {
          _textFromServer = data as String; // change the variable from the socket's callback
        });
      });
    });
    _socket.on('disconnect', (_) => print('disconnect'));
  }
  @override
  void dispose() {
    _socket.close();
    super.dispose();
  }
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: 'Welcome to Flutter',
      home: Scaffold(
        appBar: AppBar(
          title: Text(_textFromServer),
        ),
        body: Center(
          child: Text('Hello World'),
        ),
      ),
    );
  }
}
```
