### ISSUE TITLE
How to return data in flutter?

### ISSUE THREAD

**Issue by ad-on-is** [rikulo/socket.io-client-dart#57]
How to achieve something like this? I couldn't find anything in the docs

```
List<dynamic>getIO(){
        var ret = List<dynamic>();
        socket.on('test', (data) => ret = data);
        return ret;
    }
```

**Comment by jumperchen** [comment]
Using [dart-async:Completer](https://api.dart.dev/stable/2.7.1/dart-async/Completer-class.html) ?

For example,
```
Future<List<dynamic>> getIO() {
  var completer = Completer<List<dynamic>>();
  socket.on('test', (data) => completer.complete(data));
  return completer.future;
}
```

**Comment by ad-on-is** [comment]
> Using [dart-async:Completer](https://api.dart.dev/stable/2.7.1/dart-async/Completer-class.html) ?
> 
> For example,
> 
> ```
> Future<List<dynamic>> getIO() {
>   var completer = Completer<List<dynamic>>();
>   socket.on('test', (data) => completer.complete(data));
>   return completer.future;
> }
> ```

Wow, thank you... I didn't know about the Completer. Always good to learn something new ;-)
