### ISSUE TITLE
How to update opts?

### ISSUE THREAD

**Issue by ndl150694** [rikulo/socket.io-client-dart#58]
To connect the socket client to our server, we currently need to pass in the cookie as a header in the `extraHeaders` of `opts` map. We will then need to update this cookie whenever the user re-log to our system due to a new cookie being returned from our server. Should I create a new socket from scratch with this new cookie in the `opts`, or is there another way?

Thank you for porting the Socket.io JavaScript client to Dart!

**Comment by jumperchen** [comment]
You can try with this workaround with the original socket instance.
```

// change the original options with the new value
socket.io.options['extraHeaders'] = {'newFoo': 'newBar'};

// reconnect it manually.
socket.io..disconnect()..connect();
```
