### ISSUE TITLE
Retry connection backoff after 54 tries reconnections every 0 second

### ISSUE THREAD

**Issue by nebularazer** [rikulo/socket.io-client-dart#67]
In reference to the fix in af4e2ec and the corresponding discussions in #37.

When the overflow happens we end up with a reconnection **delay of 0ms**, which causes a crazy reconnect spam.

I think the second argument to Math.max should be `_max` as this overflow happens only when we at max retry delay anyways.

``` dart
return Math.max(Math.min(ms, _max), _max);
```

**Comment by jumperchen** [comment]
But, if the overflow doesn't happen, it still uses the _max value, doesn't it?
So we may change it with the following condition.
```
var temp = Math.min(ms, _max);
return temp <= 0 ? _max : temp;
```
