### ISSUE TITLE
Flutter socket.on("event", (data));

### ISSUE THREAD

**Issue by MeloHenrique** [rikulo/socket.io-client-dart#68]
I am trying to use this lib but I am not able to make my flutter app receive data from the server.
My app can emit events, but when I try to listen to events from my server with socket.on("event", (data));
My data always come empty.
How can I make my app listen to my server events ?
If I use a nodeJS client to listen to my server it works.
The problem is with Flutter.

**Comment by jumperchen** [comment]
This example works for me - https://github.com/rikulo/socket.io-client-dart/issues/36#issuecomment-588580832
