### ISSUE TITLE
Run code "server.dart"  get some error

### ISSUE THREAD

**Issue by fanbinnet** [rikulo/socket.io-client-dart#69]
[Running] dart "e:\TestProject\DratProject\socket.io-client-dart-master\test\server.dart"
/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/rikulo_commons-4.0.1/lib/src/io/http_wrapper.dart:382:8: Error: The method 'HttpHeadersWrapper.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/rikulo_commons-4.0.1/lib/src/io/http_wrapper.dart:378:8: Error: The method 'HttpHeadersWrapper.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^

[Done] exited with code=254 in 0.939 seconds

**Comment by jumperchen** [comment]
Which dart version are you using?

Dart version: `2.7.1` works well for me.

You could run `pub upgrade` to solve it if possible.

**Comment by fanbinnet** [comment]
In dart 2.8 ,the http.dart  the HttpHeaders.add and HttpHeaders.set have three parameters。
Maybe this is the root cause.

**Comment by fanbinnet** [comment]
/**
   * Sets the header [name] to [value].
   *
   * Removes all existing values for the header named [name] and
   * then [add]s [value] to it.
   */
  void set(String name, Object value,
      {@Since("2.8") bool preserveHeaderCase = false});

**Comment by jumperchen** [comment]
Please run `pub upgrade` to fix this issue.
