### ISSUE TITLE
Can't send Iterable as one packet

### ISSUE THREAD

**Issue by Curvel** [rikulo/socket.io-client-dart#72]
For sending an audio stream over socket.io we need to be able to send byte buffers. At the moment this buffers implemented as Uint8List is split by the library into one element of the List per packet.

At the moment we change this behavior for us with this  [little change](https://github.com/neohelden/socket.io-client-dart/commit/c5b87ce76533cb422df3a20f6f041b0f2d782044), but is definitely no change everybody will be happy with.

Maybe a standard option for this behavior should be added to this library. Please let me know what you think of this.

**Comment by jumperchen** [comment]
workaround:

```
socket.emitWithBinary('toServer',{'file': bytes});
```

**Comment by Curvel** [comment]
Thanks for fixing the issue :D
