### ISSUE TITLE
listening to room events

### ISSUE THREAD

**Issue by fayaz07** [rikulo/socket.io-client-dart#73]
How could I listen to events that are emitted by room, I just was able to listen to only *event*, but not other event names like room or anything else

Just like this from the official doc of socket.io
https://socket.io/docs/rooms-and-namespaces/#

**Comment by jumperchen** [comment]
It's a server-side API not client-side API, or you are looking for the server-side library - https://github.com/rikulo/socket.io-dart

**Comment by fayaz07** [comment]
Sorry I would like to listen to the events that are emitted by
```js
io.emit('event',"message");
```

but these events are not catched by the client

I tried the following
```dart
_socket.io.on('event', (data){
      print(data);
    });
_socket.on('event', (data){
      print(data);
    });
```

but i didn't recieve the message

**Comment by jumperchen** [comment]
This example works for me.

### Client code
```
import 'package:socket_io_client/socket_io_client.dart' as io;

void main() {
  var socket = io.io('http://localhost:3000', <String, dynamic>{
    'transports': ['websocket']
  });
  socket.on('fromServer', (_) => print(_));
}
```

### Server code
```
import 'package:socket_io/socket_io.dart';

void main() {
  // Dart server
  var io = Server();
  io.on('connection', (client) {
      io.sockets.emit('fromServer', 'all');
      // or
     io.emit('fromServer', 'hi all');
  });
  io.listen(3000);
}

```

**Comment by fayaz07** [comment]
Sorry I did actually used namespace and I forgot to add that on server side

**Comment by HareshGediya** [comment]
@fayaz07 Was you able to listen event that was emitted by room? How do you listen room events?

**Comment by fayaz07** [comment]
@HareshGediya , yeah I was able to listen to the events. Similarly as you listen to other events.

```
socket.on('room-event',(data){
   print(data);
});
```

**Comment by hosseinkhojany** [comment]
> 

Well, in your opinion, whether the other clients receive this event or not, it means that it is a broadcast
