### ISSUE TITLE
How to subscribe on this message?

### ISSUE THREAD

**Issue by topilski** [rikulo/socket.io-client-dart#74]
FINE: 2020-03-31 22:56:23.192: polling got data [0, 2, 7, 255, 52, 50, 91, 34, 104, 101, 108, 108, 111, 34, 44, 123, 34, 110, 97, 109, 101, 34, 58, 34, 97, 108, 101, 120, 34, 125, 93]

FINE: 2020-03-31 22:56:23.193: socket receive: type "message", data "2["hello",{"name":"alex"}]"

FINE: 2020-03-31 22:56:23.194: polling

FINE: 2020-03-31 22:56:23.194: xhr poll

**Comment by jumperchen** [comment]
Did you mean the "hello" message?
if so, it will be:
```
socket.on('hello', (data) {
    print(data);
});
```

**Comment by topilski** [comment]
Not worked, we using flask, endpoint http://206.189.193.248/socket.io/

**Comment by jumperchen** [comment]
The path `/socket.io/` you used is not for namespace part, so it should be
```
_socketIO = IO.io('http://206.189.193.248', {'path': '/socket.io'}); // by default the path is '/socket.io'
// or 
_socketIO = IO.io('http://206.189.193.248'); // same as the above
```

**Comment by topilski** [comment]
@jumperchen works! Thank you for your help!

**Comment by topilski** [comment]
In browser sockets works fine, but on mobile i received: 
`I/flutter ( 9939): connect_error: WebSocketException: Connection to 'http://206.189.193.248:0/socket.io/?EIO=3&transport=polling#' was not upgraded to websocket`

**Comment by jumperchen** [comment]
Please take a look at the usage guide first https://github.com/rikulo/socket.io-client-dart/blob/master/README.md#usage-flutter

**Comment by topilski** [comment]
![VirtualBox_Ubuntu_02_04_2020_15_58_29](https://user-images.githubusercontent.com/4686379/78252043-e7556200-74fa-11ea-85fc-079b3d48b5ed.png)

**Comment by topilski** [comment]
Fixed, was an issue on server side. `[DEBUG] Can only upgrade connection if using GET method.`

**Comment by aggarwalpulkit596** [comment]
@topilski Could you specify how did you fix this?
