### ISSUE TITLE
on method causes an error

### ISSUE THREAD

**Issue by boucoding** [rikulo/socket.io-client-dart#76]
Hi,

I am creating an app and I want to connect to the backend using your socket.io plugin.

I am using the on method to listen to data coming from the server and I can listen to it but the problem is that I want to update a list with that incoming message.

Error:
`
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: setState() called after dispose(): _NewsState#b1c7d(lifecycle state: defunct, not mounted)
E/flutter (12896): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter (12896): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter (12896): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter (12896): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1105
E/flutter (12896): #1      State.setState 
package:flutter/…/widgets/framework.dart:1140
E/flutter (12896): #2      _NewsState.checker.<anonymous closure> 
package:joiny/screens/news.dart:104
E/flutter (12896): #3      EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.dart:52
E/flutter (12896): #4      List.forEach  (dart:core-patch/growable_array.dart:283:8)
E/flutter (12896): #5      EventEmitter.emit 
package:socket_io_common/…/util/event_emitter.dart:51
E/flutter (12896): #6      Function._apply  (dart:core-patch/function_patch.dart:10:68)
E/flutter (12896): #7      Function.apply  (dart:core-patch/function_patch.dart:31:12)
E/flutter (12896): #8      Socket.onevent 
package:socket_io_client/src/socket.dart:274
E/flutter (12896): #9      Socket.onpacket 
package:socket_io_client/src/socket.dart:230
E/flutter (12896): #10     EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.dart:52
E/flutter (12896): #11     List.forEach  (dart:core-patch/growable_array.dart:283:8)
EventEmitter.emit 
package:socket_io_common/…/util/event_emitter.dart:51
E/flutter (12896): #13     Manager.ondecoded 
package:socket_io_client/src/manager.dart:320
E/flutter (12896): #14     EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.dart:52
E/flutter (12896): #15     List.forEach  (dart:core-patch/growable_array.dart:283:8)
E/flutter (12896): #16     EventEmitter.emit 
package:socket_io_common/…/util/event_emitter.dart:51
E/flutter (12896): #17     Decoder.add 
package:socket_io_common/…/parser/parser.dart:159
E/flutter (12896): #18     Manager.ondata 
package:socket_io_client/src/manager.dart:311
E/flutter (12896): #19     EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.dart:52
E/flutter (12896): #20     List.forEach  (dart:core-patch/growable_array.dart:283:8)
E/flutter (12896): #21     EventEmitter.emit 
package:socket_io_common/…/util/event_emitter.dart:51
E/flutter (12896): #22     Socket.onPacket 
package:socket_io_client/…/engine/socket.dart:467
E/flutter (12896): #23     Socket.setTransport.<anonymous closure> 
package:socket_io_client/…/engine/socket.dart:292
E/flutter (12896): #24     EventEmitter.emit.<anonymous closure> 
package:socket_io_common/…/util/event_emitter.dart:52
E/flutter (12896): #25     List.forEach  (dart:core-patch/growable_array.dart:283:8)
E/flutter (12896): #26     EventEmitter.emit 
package:socket_io_common/…/util/event_emitter.dart:51
E/flutter (12896): #27     Transport.onPacket 
package:socket_io_client/…/transport/transport.dart:128
E/flutter (12896): #28     Transport.onData 
package:socket_io_client/…/transport/transport.dart:122
E/flutter (12896): #29     IOWebSocketTransport.addEventListeners.<anonymous closure> 
package:socket_io_client/…/transport/io_websocket_transport.dart:66
E/flutter (12896): #30     _rootRunUnary  (dart:async/zone.dart:1132:38)
E/flutter (12896): #31     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (12896): #32     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (12896): #33     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
E/flutter (12896): #34     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)
E/flutter (12896): #35     _SyncStreamControllerDispatch._sendData  (dart:async/stream_controller.dart:764:19)
E/flutter (12896): #36     _StreamController._add  (dart:async/stream_controller.dart:640:7)
E/flutter (12896): #37     _StreamController.a
`

my code: 
`
Provider.of<IoProvider>(context).globalSocket.connect();
    Provider.of<IoProvider>(context).globalSocket.on('posts', (data) {
      if (data['action'] == 'add') {
          postData.add(data['data']);
      } 
      print('--emit--');
    });
`

The variable coming from provider has no issues I have tested using the real socket object which comes with the same issue.

postData is declared above the build method.

Thank You,

**Comment by boucoding** [comment]
Sorry, Issue was caused by a future call by me insie init state,

Thank you,

**Comment by boucoding** [comment]
issue regenerates only works if I reload the full app

**Comment by boucoding** [comment]
the error caused by using the plugin only not set state

**Comment by boucoding** [comment]
I am defining the listener method inside the build method is it correct?

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/issues/54#issuecomment-585516320
