### ISSUE TITLE
Subscribe to event and fetch specific data.

### ISSUE THREAD

**Issue by harshbarnwal** [rikulo/socket.io-client-dart#77]
This is not really an issue but due to bad documentation of the library I have to add this in new issue.
I want to subscribe to fetch some realtime data and there are lots of data, but i want to  subscribe to some specific data, how can i pass the the items to which I want to subscribe?

**Comment by jumperchen** [comment]
Doesn't it help for you ? - https://socket.io/docs/client-api/
This library is port of it, so the usage is the same.

**Comment by harshbarnwal** [comment]
Thanks for the quick response, I will the documentation.
