### ISSUE TITLE
how to use the ON even registration

### ISSUE THREAD

**Issue by pazhut** [rikulo/socket.io-client-dart#78]
Hi

in my flutter app once getting into a screen in the initState function i have the following code:
socket = IO.io(Server().getIoUrl(), <String, dynamic>{
      'transports': ['websocket']
    });
    socket.on('connect', (_) {
      print('connect');
    });
    for (int i=0;i<10;i++) {
      socket.emit('msg', 'test');
    }
    socket.on('fromServer',(_) => print(_));

- i would expect to see the 'fromServer' message received 10 times (i can see at the server side that it got the test message 10 times) but i only see it once, can you explain why?

- once my screen had been disposed and then re-entered (and i know the init function had been called each time my screen is loaded) i do not see the connect message or receive any of my 'fromServer' messages, do i need to do something in the dispose function? the emit is still working i can see messages being received on the server side

the corresponding core on the server side is:exports.init = function(websrv) {
	const io = require('socket.io')(websrv);
	
	io.on('connection',(socket) => {
		console.log("connected " + socket.id);
		socket.on('msg',(data) => msgRcved(data));
		socket.emit('fromServer','OK');
	});
};

function msgRcved(data) {
	console.log(data);
}

**Comment by jumperchen** [comment]
> i would expect to see the 'fromServer' message received 10 times (i can see at the server side that it got the test message 10 times) but i only see it once, can you explain why?

From your implementation, it did send once only as follow:
```
socket.on('msg',(data) => msgRcved(data)); <- received 10 times
socket.emit('fromServer','OK'); <- but send one time only.
```

**Comment by pazhut** [comment]
that is correct, i fixed that on the server side, one more question, should
i init the socket globally? and not repeatedly doing it each time i get
into my object?

**Comment by jumperchen** [comment]
It depends on how long the socket instance should be alive, if the socket connection is very short, it should be closed each time you finish your job, if not, then it can stay longer. i.e. the same question as how do you deal with your DB connection.

**Comment by pazhut** [comment]
Thanks much
