### ISSUE TITLE
dart client use namespace

### ISSUE THREAD

**Issue by pbeppe** [rikulo/socket.io-client-dart#80]
Hi, 
       how i can use namespace into client with dart? there is a documentation of dart?
thank you for help

**Comment by jumperchen** [comment]
It's the same as the [Socket.io JS](https://socket.io/docs/#Restricting-yourself-to-a-namespace)
For example,
```
IO.Socket socket = IO.io('http://localhost:3000/your-namespace');
    socket.on('connect', (_) {
     print('connect');
     socket.emit('msg', 'test');
    });
```

**Comment by pbeppe** [comment]
ok in nodejs server  shell i use .of()?

**Comment by jumperchen** [comment]
Yes, as the same as the `Socket.io JS`'s docs.

**Comment by pbeppe** [comment]
i connect but i don't receive and send message

**Comment by pbeppe** [comment]
i resolved thank

**Comment by mhbdev** [comment]
How not to create a socket object for every namespace I am going to use.
Should I create IO.io('http://localhost:3000/namespace1') for namespace1 and IO.io('http://localhost:3000/namespace2')?
I really do not want to have 2 connections and I need to access that on connection through just one socket object cuz they both are referring to the same host:port Only with different namespaces! why would I create new Socket object? Is there any best practice for handling muliple namespaces with One socket object?
