### ISSUE TITLE
WebSocket exception When trying to connect

### ISSUE THREAD

**Issue by vksBhardwaj** [rikulo/socket.io-client-dart#82]
Hi
When i try to connect with server the following exception thrown by library

`WebSocketException: Connection to 'https://api.myserver.app:0/socket.io/?userId=5ea29bbb9ac2ac2f7274dc65&EIO=3&transport=polling#' was not upgraded to websocket
`
**I dont know why `:0` add after `app` in the URL**

Code For connect

    ```
_socket = IO.io(ApiConstants.BASE_URL, <String, dynamic>{
      'transports': ['polling'],
      'query':{"userId": mineUserId}, // optional
    });
```

**Comment by jumperchen** [comment]
FYI: https://github.com/rikulo/socket.io-client-dart/blob/master/README.md
Please take a look first.
