### ISSUE TITLE
Ability to use self signed cert

### ISSUE THREAD

**Issue by lehno** [rikulo/socket.io-client-dart#84]
I would like to have the option rejectUnauthorized like web. It helps for developing using https localhost

**Comment by jumperchen** [comment]
FYI: https://github.com/dart-lang/sdk/issues/34284
It may not be this library problem.

**Comment by lehno** [comment]
Socket.io for web has this options, it would be good to have it here as well.
For now the fix is this:

`class MyHttpOverrides extends HttpOverrides {
  @override
  HttpClient createHttpClient(SecurityContext context) {
    return super.createHttpClient(context)
      ..badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
  }
}

void main() {
  HttpOverrides.global = new MyHttpOverrides();
  runApp(MyApp());
}`

**Comment by kbrmimbyl** [comment]
@lehno you just saved me a ton of pain, thanks!

**Comment by iqbalabdurrazaq** [comment]
> Socket.io for web has this options, it would be good to have it here as well.
> For now the fix is this:
> 
> ```
> class MyHttpOverrides extends HttpOverrides {
>   @override
>   HttpClient createHttpClient(SecurityContext context) {
>     return super.createHttpClient(context)
>       ..badCertificateCallback =
>           (X509Certificate cert, String host, int port) => true;
>   }
> }
> 
> void main() {
>   HttpOverrides.global = new MyHttpOverrides();
>   runApp(MyApp());
> }
> ```

i get error in "createHttpClient", anyone solve this ?,.
thanks

**Comment by ElsayedDev** [comment]
> > Socket.io for web has this options, it would be good to have it here as well.
> > For now the fix is this:
> > ```
> > class MyHttpOverrides extends HttpOverrides {
> >   @override
> >   HttpClient createHttpClient(SecurityContext context) {
> >     return super.createHttpClient(context)
> >       ..badCertificateCallback =
> >           (X509Certificate cert, String host, int port) => true;
> >   }
> > }
> > 
> > void main() {
> >   HttpOverrides.global = new MyHttpOverrides();
> >   runApp(MyApp());
> > }
> > ```
> 
> i get error in "createHttpClient", anyone solve this ?,. thanks

Just change `SecurityContext` to **`SecurityContext?`** and it will work

**Comment by Mumunt** [comment]
this solution need to import dart.io

but how about flutter web?
