### ISSUE TITLE
Send file as buffer

### ISSUE THREAD

**Issue by Z3rolive** [rikulo/socket.io-client-dart#85]
Here is how file transfer is being done on node.js client. Is there any way in this library to achieve the same results?
```
const data = {
            file: file.name
          };
          const stream = ss.createStream();
          ss(socket).emit("send-file", stream, data);
          ss.createBlobReadStream(file).pipe(stream);
```

**Comment by jumperchen** [comment]
For example,
```
// Server code
List<int> bytes = [];
    client.on('msg', (data) {
      bytes.addAll(data);
    });
    client.on('done', (_) {
      new File("/foo/xx.png").writeAsBytesSync(bytes);
    })

// Client code
  socket.on('connect', (s) {
    var openRead = File('../foo-icon.png').openRead();
    openRead.listen((bytes) {
      print('send');
      socket.emitWithBinary('msg', bytes);
    }, onDone: () => socket.emit('done'));
  });
```

**Comment by Z3rolive** [comment]
It still doesn't work. emitWithBinary takes iterable string while openRead gives List<int>.

**Comment by Z3rolive** [comment]
> For example,
> 
> ```
> // Server code
> List<int> bytes = [];
>     client.on('msg', (data) {
>       bytes.addAll(data);
>     });
>     client.on('done', (_) {
>       new File("/foo/xx.png").writeAsBytesSync(bytes);
>     })
> 
> // Client code
>   socket.on('connect', (s) {
>     var openRead = File('../foo-icon.png').openRead();
>     openRead.listen((bytes) {
>       print('send');
>       socket.emitWithBinary('msg', bytes);
>     }, onDone: () => socket.emit('done'));
>   });
> ```
It still doesn't work. emitWithBinary takes iterable string while openRead gives List.

**Comment by jumperchen** [comment]
Did you use latest version? If so, the code above works to me.
