### ISSUE TITLE
Is there a way to run auto connection under app backend mode?

### ISSUE THREAD

**Issue by stoneLee81** [rikulo/socket.io-client-dart#88]
When app switch to app backend mode, it will be frozen by os system, and auto connection will be disabled, is there a way or tool to achieve this process is alive when it was running under backend mode?

**Comment by GargNishant** [comment]
This is actually related to the platform you are running. In Android background apps are stopped and in iOS they might work in Different way. The solution might not be a generic one. In Android you can run a Foreground Service. There are packages which can make it, but they only exists for Android and not iOS. But for iOS, you might need to see how it handles Background apps, and make changes for that platform separately.
