### ISSUE TITLE
Getting issue with Dart Client

### ISSUE THREAD

**Issue by faiziakbr** [rikulo/socket.io-client-dart#9]
Hello, I am trying to connect to the socket by just calling these lines
IO.Socket socket = IO.io(SOCKET_URL);
    socket.connect();
But getting error in flutter.
![capture1](https://user-images.githubusercontent.com/25583358/49479565-480c5600-f845-11e8-927a-2775dbd07089.PNG)

**Comment by jumperchen** [comment]
Duplicated #4
